/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/audit/events/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET /api/v1/audit/events/{id} — 审计事件详情 */
        get: operations["get_audit_event"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cold-chain/points": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET /api/v1/cold-chain/points — 冷链温度时序 */
        get: operations["list_cold_chain_points"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET /api/v1/items — 分页列表 */
        get: operations["list_items"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/items/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET /api/v1/items/{id} — 单条商品查询 */
        get: operations["get_item"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/items/{id}/isolate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** POST /api/v1/items/{id}/isolate — 隔离（演示 tagged union 写入） */
        post: operations["isolate_item"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description 审计事件（H2-001 append-only）
         *
         *     diff 字段存任意 JSON：utoipa 应当能识别 serde_json::Value 并映射为 OpenAPI
         *     的 `additionalProperties: true` 或 `type: object`（具体生成形式留给 spike 验证）
         */
        Audit: {
            action: string;
            /** Format: uuid */
            actor_id: string;
            actor_name: string;
            /** @description 任意 JSON diff（before / after / changed_keys） */
            diff: Record<string, never>;
            /** Format: uuid */
            id: string;
            /** Format: date-time */
            occurred_at: string;
        };
        /** @description 冷链温度采样点（M5-002 冷链监控） */
        ColdChainPoint: {
            /** @description 是否超阈 */
            out_of_range: boolean;
            /**
             * Format: date-time
             * @description 采样时间（UTC）
             */
            t: string;
            /**
             * Format: double
             * @description 温度（摄氏度）
             */
            v: number;
        };
        /** @description 错误响应（统一格式；ADR-0010 错误码模式） */
        ErrorResponse: {
            /** @description 错误码（如 M1-001-VR-014） */
            code: string;
            /** @description 错误消息（中文） */
            message: string;
        };
        /**
         * @description 库存状态（tagged union — 验证 utoipa 对带数据 enum 的支持）
         *
         *     serde 默认外部 tag："Qualified" / { "Isolated": { "reason": "..." } }
         *     可通过 #[serde(tag = "type")] 改为内部 tag（可读性更好但需测试）
         */
        InventoryStatus: {
            /** @enum {string} */
            type: "Qualified";
        } | {
            /** @description 隔离（含原因） */
            data: {
                reason: string;
            };
            /** @enum {string} */
            type: "Isolated";
        } | {
            /** @enum {string} */
            type: "Quarantined";
        } | {
            /** @description 销毁待审批 */
            data: {
                /** Format: uuid */
                approver_id: string;
            };
            /** @enum {string} */
            type: "PendingDestruction";
        };
        /** @description 商品档案（M1-001 商品档案最小集） */
        Item: {
            /** @description 批号（部分商品无批号） */
            batch_no?: string | null;
            /** @description 商品编码（如 P-001234） */
            code: string;
            /**
             * Format: date
             * @description 有效期（NaiveDate；时区由仓库默认时区决定）
             */
            expiry: string;
            /**
             * Format: uuid
             * @description 商品唯一 ID（UUID v4）
             */
            id: string;
            /** @description 品名 */
            name: string;
            status: components["schemas"]["InventoryStatus"];
            /**
             * Format: int32
             * @description 库存数量
             */
            stock: number;
        };
        /**
         * @description 分页结果（包装 Item 列表）
         *
         *     注：utoipa 对泛型类型的支持需要 #[aliases] + lifetime bound（utoipa 4.2
         *     的 ToSchema trait 带 lifetime）。本 spike 直接用非泛型版本，避免 spike
         *     复杂度过高；Wave 1 落地时如有大量分页类型可再评估泛型方案。
         */
        PaginatedItems: {
            /** @description 数据列表 */
            data: components["schemas"]["Item"][];
            /**
             * Format: int32
             * @description 当前页（从 1 起）
             */
            page: number;
            /**
             * Format: int32
             * @description 每页大小
             */
            page_size: number;
            /**
             * Format: int64
             * @description 总数
             */
            total: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_audit_event: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 审计事件 UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Audit"];
                };
            };
            /** @description 未找到 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_cold_chain_points: {
        parameters: {
            query: {
                /** @description 起始时间 RFC3339 */
                from: string;
                /** @description 结束时间 RFC3339 */
                to: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ColdChainPoint"][];
                };
            };
        };
    };
    list_items: {
        parameters: {
            query?: {
                /** @description 页码（默认 1） */
                page?: number | null;
                /** @description 每页大小（默认 20，最大 100） */
                page_size?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedItems"];
                };
            };
        };
    };
    get_item: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 商品 UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Item"];
                };
            };
            /** @description 未找到 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    isolate_item: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 商品 UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InventoryStatus"];
            };
        };
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Item"];
                };
            };
            /** @description 参数错误 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
