[package]
name = "wms-customer-portal-api"
version.workspace = true
edition.workspace = true
publish = false

[[bin]]
name = "wms-customer-portal-api"
path = "src/main.rs"

[dependencies]
axum.workspace = true
bcrypt.workspace = true
chrono.workspace = true
hex.workspace = true
jsonwebtoken.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
sqlx.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tracing.workspace = true
uuid.workspace = true
zip.workspace = true

[dev-dependencies]
tower.workspace = true
