/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["portalHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["portalLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/internal/projections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ingestPortalProjection"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/addresses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listPortalAddresses"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listPortalOrders"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/{order_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getPortalOrder"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/report-versions/{report_version_id}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["authorizePortalReportDownload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/files/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 凭下载会话 token 流式获取文件
         * @description 校验 token 未过期后从 H-FILE 只读存储根流式读取；不访问 WMS。
         *     不经过对象存储预签名直出（首期基线）。
         */
        get: operations["downloadPortalFile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/exports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listPortalExports"];
        put?: never;
        post: operations["createPortalExport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/exports/{export_id}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["authorizePortalExportDownload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listPortalUsers"];
        put?: never;
        post: operations["createPortalUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["updatePortalUser"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            code: string;
            message: string;
        };
        LoginRequest: {
            username: string;
            /** Format: password */
            password: string;
        };
        LoginResponse: {
            access_token: string;
            /** Format: date-time */
            expires_at: string;
            user: components["schemas"]["PortalUser"];
        };
        PortalUser: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            customer_id: string;
            username: string;
            display_name: string;
            /** @enum {string} */
            role: "customer_admin" | "customer_user";
            /** @enum {string} */
            status: "active" | "disabled" | "locked";
            can_view_report_history: boolean;
            address_ids: string[];
        };
        CreateUserRequest: {
            username: string;
            display_name: string;
            /** Format: password */
            password: string;
            /** @enum {string} */
            role: "customer_admin" | "customer_user";
            /**
             * @description 缺省时默认为 false
             * @default false
             */
            can_view_report_history: boolean;
            /**
             * @description 缺省时默认为空数组
             * @default []
             */
            address_ids: string[];
        };
        UpdateUserRequest: {
            display_name: string;
            /** @enum {string} */
            role: "customer_admin" | "customer_user";
            /** @enum {string} */
            status: "active" | "disabled";
            can_view_report_history: boolean;
            address_ids: string[];
        };
        ProjectionRequest: {
            /** Format: uuid */
            event_id: string;
            /** @enum {string} */
            event_type: "customer_order.snapshot" | "customer.upsert" | "customer_address.upsert" | "outbound_order.upsert" | "drug_inspection_report.upsert";
            /** Format: date-time */
            occurred_at: string;
            payload: {
                [key: string]: unknown;
            };
        };
        ProjectionResponse: {
            /** Format: uuid */
            event_id: string;
            duplicate: boolean;
            /** @enum {string} */
            status: "succeeded";
        };
        AddressSummary: {
            /** Format: uuid */
            id: string;
            address_code: string;
            /** @description 订单冻结的送货地址名称，取自订单地址快照 */
            address_name: string;
        };
        OrderSummary: {
            /** Format: uuid */
            id: string;
            order_no: string;
            /** @enum {string} */
            status: "shipped" | "signed";
            customer_code: string;
            customer_name: string;
            /** Format: uuid */
            delivery_address_id: string;
            address_code: string;
            address_name: string;
            product_codes: string[];
            product_names: string[];
            batch_nos: string[];
            quantities: number[];
            /** Format: date-time */
            shipped_at: string;
            /** Format: date-time */
            signed_at?: string | null;
            /** Format: int64 */
            line_count: number;
            /** Format: int64 */
            available_report_count: number;
            /** Format: int64 */
            pending_report_count: number;
        };
        OrderDetail: {
            /** Format: uuid */
            id: string;
            order_no: string;
            /** @enum {string} */
            status: "shipped" | "signed";
            /** Format: uuid */
            delivery_address_id: string;
            address_snapshot: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            shipped_at: string;
            /** Format: date-time */
            signed_at?: string | null;
            lines: components["schemas"]["OrderLine"][];
        };
        OrderLine: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            product_id: string;
            product_code: string;
            product_name: string;
            batch_no: string;
            /** Format: double */
            quantity: number;
            reports: components["schemas"]["ReportSummary"][];
        };
        ReportSummary: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            report_id: string;
            version_number: number;
            report_no: string;
            /** @enum {string} */
            status: "confirmed" | "superseded";
            is_current: boolean;
            modification_reason?: string | null;
            /** @enum {string} */
            customer_copy_status: "queued" | "processing" | "available" | "failed";
            customer_copy_file_name?: string | null;
            /** Format: int64 */
            customer_copy_size?: number | null;
            digitally_signed_original: boolean;
            /** Format: date-time */
            confirmed_at: string;
        };
        CreateExportRequest: {
            order_ids: string[];
            /** @default false */
            include_history: boolean;
        };
        ExportJob: {
            /** Format: uuid */
            id: string;
            include_history: boolean;
            /** @enum {string} */
            status: "queued" | "processing" | "completed" | "failed";
            requested_order_count: number;
            report_file_count: number;
            missing_count: number;
            /** Format: int64 */
            total_size: number;
            result_file_name?: string | null;
            last_error?: string | null;
            /** Format: date-time */
            expires_at?: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            finished_at?: string | null;
        };
        DownloadUrl: {
            /**
             * @description 客户平台相对下载路径（`/api/v1/files/{token}`），约 15 分钟有效，
             *     不得持久化或当作对象存储预签名 URL 使用。
             */
            url: string;
            file_name: string;
            /** Format: date-time */
            expires_at: string;
        };
    };
    responses: {
        /** @description 未登录、令牌失效或账号已停用 */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 没有客户、地址、历史版本或管理员权限 */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 资源不存在或不在授权范围 */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 请求字段或 200 份/2GB 等受控上限不满足 */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        OrderId: string;
        ReportVersionId: string;
        ExportId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    portalHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 服务可用 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status: "ok";
                    };
                };
            };
        };
    };
    portalLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description 登录成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    ingestPortalProjection: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectionRequest"];
            };
        };
        responses: {
            /** @description 投影成功或事件已幂等消费 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectionResponse"];
                };
            };
            /** @description 请求校验失败（VALIDATION_ERROR）或事件数据格式错误（INVALID_PROJECTION_PAYLOAD） */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description 投影事件已进入死信队列，需人工重放 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listPortalAddresses: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 当前账号可见地址 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AddressSummary"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listPortalOrders: {
        parameters: {
            query?: {
                address_id?: string;
                status?: "shipped" | "signed";
                keyword?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 授权地址下已发货或已签收订单 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderSummary"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getPortalOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_id: components["parameters"]["OrderId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 订单、批号和可见药检单版本 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderDetail"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    authorizePortalReportDownload: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_version_id: components["parameters"]["ReportVersionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /**
             * @description 15 分钟有效下载会话。`url` 为客户平台相对路径（如 `/api/v1/files/{token}`），
             *     不是对象存储预签名 URL；客户端须再请求该路径由本服务流式回传文件。
             */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DownloadUrl"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    downloadPortalFile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已授权的 PDF 或 ZIP 字节 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/pdf": string;
                    "application/zip": string;
                };
            };
            /** @description 下载地址不存在、越权或已过期 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listPortalExports: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 当前账号导出任务 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExportJob"][];
                };
            };
        };
    };
    createPortalExport: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateExportRequest"];
            };
        };
        responses: {
            /** @description 已创建异步导出任务 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExportJob"];
                };
            };
            400: components["responses"]["ValidationError"];
            403: components["responses"]["Forbidden"];
        };
    };
    authorizePortalExportDownload: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                export_id: components["parameters"]["ExportId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /**
             * @description 15 分钟有效 ZIP 下载会话；`url` 为客户平台 `/api/v1/files/{token}`，
             *     由本服务流式回传，非对象存储预签名。
             */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DownloadUrl"];
                };
            };
            /** @description 导出任务不存在、越权、未完成或已过 7 天保留期 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listPortalUsers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 当前客户组织账号 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortalUser"][];
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
    createPortalUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserRequest"];
            };
        };
        responses: {
            /** @description 账号已创建 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortalUser"];
                };
            };
            400: components["responses"]["ValidationError"];
            403: components["responses"]["Forbidden"];
            /** @description 用户名已存在 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updatePortalUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserRequest"];
            };
        };
        responses: {
            /** @description 账号、地址范围和历史权限已更新 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortalUser"];
                };
            };
            400: components["responses"]["ValidationError"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
}
