import type { MatrixPrototypeSpec } from "./types";

export const SPECS: MatrixPrototypeSpec[] = [
  {
    storyId: "US-M3-001",
    title: "实时库存查询",
    end: "pc",
    reason: "多维筛选+批次展开",
    priority: "P2",
    group: "M3 实时库存查询",
    moduleCode: "M3",
    slug: "pc-m3-001",
  },
  {
    storyId: "US-M3-002",
    title: "批次与效期管理",
    end: "pc",
    reason: "批次列表+近效期预警",
    priority: "P2",
    group: "M3 批次与效期管理",
    moduleCode: "M3",
    slug: "pc-m3-002",
  },
  {
    storyId: "US-M3-003",
    title: "库存状态管理",
    end: "pc",
    reason: "状态流转+隔离/解隔离",
    priority: "P2",
    group: "M3 库存状态管理",
    moduleCode: "M3",
    slug: "pc-m3-003",
  },
  {
    storyId: "US-M3-004",
    title: "在库养护",
    end: "pda",
    reason: "PDA 养护记录+PC 计划",
    priority: "P2",
    group: "M3 在库养护",
    moduleCode: "M3",
    slug: "pda-m3-004",
  },
  {
    storyId: "US-M3-004",
    title: "在库养护",
    end: "pc",
    reason: "PDA 养护记录+PC 计划",
    priority: "P2",
    group: "M3 在库养护",
    moduleCode: "M3",
    slug: "pc-m3-004",
  },
  {
    storyId: "US-M3-005",
    title: "库存盘点",
    end: "pda",
    reason: "PDA 盘点扫码+差异处理",
    priority: "P2",
    group: "M3 库存盘点",
    moduleCode: "M3",
    slug: "pda-m3-005",
  },
  {
    storyId: "US-M3-006",
    title: "库内移库",
    end: "pda",
    reason: "PDA 扫码移库",
    priority: "P2",
    group: "M3 库内移库",
    moduleCode: "M3",
    slug: "pda-m3-006",
  },
  {
    storyId: "US-M3-009",
    title: "库存预警",
    end: "pc",
    reason: "预警规则+告警列表",
    priority: "P2",
    group: "M3 库存预警",
    moduleCode: "M3",
    slug: "pc-m3-009",
  },
  {
    storyId: "US-M3-010",
    title: "ABC 分类管理",
    end: "pc",
    reason: "分类规则+结果展示",
    priority: "P2",
    group: "M3 ABC 分类管理",
    moduleCode: "M3",
    slug: "pc-m3-010",
  },
  {
    storyId: "US-M3-011",
    title: "库位历史追踪",
    end: "pc",
    reason: "库位时间线",
    priority: "P2",
    group: "M3 库位历史追踪",
    moduleCode: "M3",
    slug: "pc-m3-011",
  },
  {
    storyId: "US-M4-001",
    title: "出库订单管理",
    end: "pc",
    reason: "订单列表+状态筛选+详情",
    priority: "P3",
    group: "M4 出库订单管理",
    moduleCode: "M4",
    slug: "pc-m4-001",
  },
  {
    storyId: "US-M4-002",
    title: "波次规划",
    end: "pc",
    reason: "波次创建+订单分配+策略",
    priority: "P3",
    group: "M4 波次规划",
    moduleCode: "M4",
    slug: "pc-m4-002",
  },
  {
    storyId: "US-M4-003",
    title: "PDA 拣选作业",
    end: "pda",
    reason: "PDA 拣选路径+扫码确认",
    priority: "P3",
    group: "M4 PDA 拣选作业",
    moduleCode: "M4",
    slug: "pda-m4-003",
  },
  {
    storyId: "US-M4-004",
    title: "出库复核",
    end: "pda",
    reason: "PDA/PAD 扫码复核",
    priority: "P3",
    group: "M4 出库复核",
    moduleCode: "M4",
    slug: "pda-m4-004",
  },
  {
    storyId: "US-M4-004",
    title: "出库复核",
    end: "pad",
    reason: "PDA/PAD 扫码复核",
    priority: "P3",
    group: "M4 出库复核",
    moduleCode: "M4",
    slug: "pad-m4-004",
  },
  {
    storyId: "US-M4-005",
    title: "随货同行单打印",
    end: "pc",
    reason: "打印预览+GSP 格式",
    priority: "P3",
    group: "M4 随货同行单打印",
    moduleCode: "M4",
    slug: "pc-m4-005",
  },
  {
    storyId: "US-M4-005",
    title: "随货同行单打印",
    end: "pad",
    reason: "打印预览+GSP 格式",
    priority: "P3",
    group: "M4 随货同行单打印",
    moduleCode: "M4",
    slug: "pad-m4-005",
  },
  {
    storyId: "US-M4-006",
    title: "发货与交接",
    end: "pda",
    reason: "PDA 交接扫码+PC 确认",
    priority: "P3",
    group: "M4 发货与交接",
    moduleCode: "M4",
    slug: "pda-m4-006",
  },
  {
    storyId: "US-M4-006",
    title: "发货与交接",
    end: "pc",
    reason: "PDA 交接扫码+PC 确认",
    priority: "P3",
    group: "M4 发货与交接",
    moduleCode: "M4",
    slug: "pc-m4-006",
  },
  {
    storyId: "US-M4-007",
    title: "出库进度看板",
    end: "pc",
    reason: "实时进度大屏",
    priority: "P3",
    group: "M4 出库进度看板",
    moduleCode: "M4",
    slug: "pc-m4-007",
  },
  {
    storyId: "US-M4-007",
    title: "出库进度看板",
    end: "pad",
    reason: "实时进度大屏",
    priority: "P3",
    group: "M4 出库进度看板",
    moduleCode: "M4",
    slug: "pad-m4-007",
  },
  {
    storyId: "US-M4-008",
    title: "出库退货处理",
    end: "pda",
    reason: "PDA 退货验收+PC 审批",
    priority: "P3",
    group: "M4 出库退货处理",
    moduleCode: "M4",
    slug: "pda-m4-008",
  },
  {
    storyId: "US-M4-008",
    title: "出库退货处理",
    end: "pc",
    reason: "PDA 退货验收+PC 审批",
    priority: "P3",
    group: "M4 出库退货处理",
    moduleCode: "M4",
    slug: "pc-m4-008",
  },
  {
    storyId: "US-M4-010",
    title: "拣选路径策略",
    end: "pc",
    reason: "路径可视化+策略配置",
    priority: "P3",
    group: "M4 拣选路径策略",
    moduleCode: "M4",
    slug: "pc-m4-010",
  },
  {
    storyId: "US-M4-011",
    title: "合并发货与拆单",
    end: "pc",
    reason: "合并/拆单规则+预览",
    priority: "P3",
    group: "M4 合并发货与拆单",
    moduleCode: "M4",
    slug: "pc-m4-011",
  },
  {
    storyId: "US-M5-001",
    title: "冷链设备台账",
    end: "pc",
    reason: "设备列表+校准记录",
    priority: "P2",
    group: "M5 冷链设备台账",
    moduleCode: "M5",
    slug: "pc-m5-001",
  },
  {
    storyId: "US-M5-002",
    title: "温控数据接入与展示",
    end: "pc",
    reason: "温度曲线+实时监控",
    priority: "P2",
    group: "M5 温控数据接入与展示",
    moduleCode: "M5",
    slug: "pc-m5-002",
  },
  {
    storyId: "US-M5-003",
    title: "温度超标事件接入与联动",
    end: "pc",
    reason: "超标告警+批次隔离联动",
    priority: "P2",
    group: "M5 温度超标事件接入与联动",
    moduleCode: "M5",
    slug: "pc-m5-003",
  },
  {
    storyId: "US-M6-001",
    title: "GSP 法定台账自动生成",
    end: "pc",
    reason: "台账模板+生成+导出",
    priority: "P1",
    group: "M6 GSP 法定台账自动生成",
    moduleCode: "M6",
    slug: "pc-m6-001",
  },
  {
    storyId: "US-M6-002",
    title: "审计追踪查询",
    end: "pc",
    reason: "高级查询+时间线（与H2-002联动）",
    priority: "P1",
    group: "M6 审计追踪查询",
    moduleCode: "M6",
    slug: "pc-m6-002",
  },
  {
    storyId: "US-M6-003",
    title: "业务报表",
    end: "pc",
    reason: "多维报表+图表+导出",
    priority: "P1",
    group: "M6 业务报表",
    moduleCode: "M6",
    slug: "pc-m6-003",
  },
  {
    storyId: "US-M6-004",
    title: "特殊管理药品专用台账",
    end: "pc",
    reason: "麻精/放射/血液制品专用格式",
    priority: "P1",
    group: "M6 特殊管理药品专用台账",
    moduleCode: "M6",
    slug: "pc-m6-004",
  },
  {
    storyId: "US-M8-001",
    title: "自动补货算法（门店水位）",
    end: "pc",
    reason: "水位配置+补货建议预览",
    priority: "P4",
    group: "M8 自动补货算法",
    moduleCode: "M8",
    slug: "pc-m8-001",
  },
  {
    storyId: "US-M8-002",
    title: "越库作业（Cross-Docking）",
    end: "pda",
    reason: "PDA 越库扫码+PC 调度",
    priority: "P4",
    group: "M8 越库作业",
    moduleCode: "M8",
    slug: "pda-m8-002",
  },
  {
    storyId: "US-M8-002",
    title: "越库作业（Cross-Docking）",
    end: "pc",
    reason: "PDA 越库扫码+PC 调度",
    priority: "P4",
    group: "M8 越库作业",
    moduleCode: "M8",
    slug: "pc-m8-002",
  },
  {
    storyId: "US-M9-001",
    title: "计费规则配置",
    end: "pc",
    reason: "多维计费规则编辑器",
    priority: "P2",
    group: "M9 计费规则配置",
    moduleCode: "M9",
    slug: "pc-m9-001",
  },
  {
    storyId: "US-M9-003",
    title: "账单管理",
    end: "pc",
    reason: "账单列表+明细+对账+导出",
    priority: "P2",
    group: "M9 账单管理",
    moduleCode: "M9",
    slug: "pc-m9-003",
  },
  {
    storyId: "US-M10-002",
    title: "在途温控数据接入",
    end: "pc",
    reason: "在途温度曲线+地图",
    priority: "P4",
    group: "M10 在途温控数据接入",
    moduleCode: "M10",
    slug: "pc-m10-002",
  },
  {
    storyId: "US-M10-003",
    title: "容器回收追踪",
    end: "pc",
    reason: "PDA 扫码回收+PC 追踪",
    priority: "P4",
    group: "M10 容器回收追踪",
    moduleCode: "M10",
    slug: "pc-m10-003",
  },
  {
    storyId: "US-M10-003",
    title: "容器回收追踪",
    end: "pda",
    reason: "PDA 扫码回收+PC 追踪",
    priority: "P4",
    group: "M10 容器回收追踪",
    moduleCode: "M10",
    slug: "pda-m10-003",
  },
  {
    storyId: "US-M10-004",
    title: "出库订单与 TMS 协作",
    end: "pc",
    reason: "订单推送状态+调度结果",
    priority: "P4",
    group: "M10 出库订单与 TMS 协作",
    moduleCode: "M10",
    slug: "pc-m10-004",
  },
  {
    storyId: "US-TE-004",
    title: "任务优先级规则",
    end: "pc",
    reason: "优先级规则编辑器",
    priority: "P2",
    group: "TE 任务优先级规则",
    moduleCode: "TE",
    slug: "pc-te-004",
  },
  {
    storyId: "US-TE-005",
    title: "任务分配",
    end: "pc",
    reason: "分配策略+手动调整",
    priority: "P2",
    group: "TE 任务分配",
    moduleCode: "TE",
    slug: "pc-te-005",
  },
  {
    storyId: "US-TE-006",
    title: "任务释放控制",
    end: "pc",
    reason: "释放规则+队列管理",
    priority: "P2",
    group: "TE 任务释放控制",
    moduleCode: "TE",
    slug: "pc-te-006",
  },
  {
    storyId: "US-TE-007",
    title: "任务合并",
    end: "pc",
    reason: "合并规则+预览",
    priority: "P2",
    group: "TE 任务合并",
    moduleCode: "TE",
    slug: "pc-te-007",
  },
  {
    storyId: "US-TE-008",
    title: "任务执行（PDA）",
    end: "pda",
    reason: "PDA 任务列表+执行+完成",
    priority: "P2",
    group: "TE 任务执行",
    moduleCode: "TE",
    slug: "pda-te-008",
  },
  {
    storyId: "US-TE-009",
    title: "任务跟踪看板",
    end: "pc",
    reason: "实时任务大屏",
    priority: "P2",
    group: "TE 任务跟踪看板",
    moduleCode: "TE",
    slug: "pc-te-009",
  },
  {
    storyId: "US-TE-009",
    title: "任务跟踪看板",
    end: "pad",
    reason: "实时任务大屏",
    priority: "P2",
    group: "TE 任务跟踪看板",
    moduleCode: "TE",
    slug: "pad-te-009",
  },
  {
    storyId: "US-TE-010",
    title: "任务绩效统计",
    end: "pc",
    reason: "绩效报表+排名",
    priority: "P2",
    group: "TE 任务绩效统计",
    moduleCode: "TE",
    slug: "pc-te-010",
  },
  {
    storyId: "US-RP-001",
    title: "补货阈值管理",
    end: "pc",
    reason: "阈值配置+批量设置",
    priority: "P2",
    group: "RP 补货阈值管理",
    moduleCode: "RP",
    slug: "pc-rp-001",
  },
  {
    storyId: "US-RP-002",
    title: "日常补货（阈值触发）",
    end: "pda",
    reason: "PDA 补货任务执行",
    priority: "P2",
    group: "RP 日常补货",
    moduleCode: "RP",
    slug: "pda-rp-002",
  },
  {
    storyId: "US-RP-003",
    title: "波次补货（紧急触发）",
    end: "pda",
    reason: "PDA 紧急补货",
    priority: "P2",
    group: "RP 波次补货",
    moduleCode: "RP",
    slug: "pda-rp-003",
  },
  {
    storyId: "US-RP-004",
    title: "拣选补拣（兜底触发）",
    end: "pda",
    reason: "PDA 补拣",
    priority: "P2",
    group: "RP 拣选补拣",
    moduleCode: "RP",
    slug: "pda-rp-004",
  },
  {
    storyId: "US-RP-005",
    title: "补货记录与报表",
    end: "pc",
    reason: "补货记录列表+统计",
    priority: "P2",
    group: "RP 补货记录与报表",
    moduleCode: "RP",
    slug: "pc-rp-005",
  },
  {
    storyId: "US-PK-001",
    title: "包装站工位管理",
    end: "pc",
    reason: "工位配置+状态",
    priority: "P3",
    group: "PK 包装站工位管理",
    moduleCode: "PK",
    slug: "pc-pk-001",
  },
  {
    storyId: "US-PK-001",
    title: "包装站工位管理",
    end: "pad",
    reason: "工位配置+状态",
    priority: "P3",
    group: "PK 包装站工位管理",
    moduleCode: "PK",
    slug: "pad-pk-001",
  },
  {
    storyId: "US-PK-002",
    title: "装箱作业",
    end: "pad",
    reason: "PAD 装箱扫码+Put-to-Light",
    priority: "P3",
    group: "PK 装箱作业",
    moduleCode: "PK",
    slug: "pad-pk-002",
  },
  {
    storyId: "US-PK-003",
    title: "称重校验",
    end: "pad",
    reason: "电子秤对接+差异提示",
    priority: "P3",
    group: "PK 称重校验",
    moduleCode: "PK",
    slug: "pad-pk-003",
  },
  {
    storyId: "US-PK-004",
    title: "保温箱配置（冷链）",
    end: "pc",
    reason: "保温箱规格+温区匹配",
    priority: "P3",
    group: "PK 保温箱配置",
    moduleCode: "PK",
    slug: "pc-pk-004",
  },
  {
    storyId: "US-PK-005",
    title: "追溯码出库核验",
    end: "pad",
    reason: "PAD 扫码核验",
    priority: "P3",
    group: "PK 追溯码出库核验",
    moduleCode: "PK",
    slug: "pad-pk-005",
  },
  {
    storyId: "US-PK-006",
    title: "快递面单打印",
    end: "pad",
    reason: "面单预览+打印",
    priority: "P3",
    group: "PK 快递面单打印",
    moduleCode: "PK",
    slug: "pad-pk-006",
  },
  {
    storyId: "US-VR-001",
    title: "校验规则配置",
    end: "pc",
    reason: "规则编辑器+条件组合",
    priority: "P2",
    group: "VR 校验规则配置",
    moduleCode: "VR",
    slug: "pc-vr-001",
  },
  {
    storyId: "US-VR-003",
    title: "校验异常人工处理",
    end: "pc",
    reason: "异常队列+处理表单",
    priority: "P2",
    group: "VR 校验异常人工处理",
    moduleCode: "VR",
    slug: "pc-vr-003",
  },
  {
    storyId: "US-VR-005",
    title: "校验规则测试",
    end: "pc",
    reason: "规则沙箱测试+结果",
    priority: "P2",
    group: "VR 校验规则测试",
    moduleCode: "VR",
    slug: "pc-vr-005",
  },
  {
    storyId: "US-VR-006",
    title: "双人策略矩阵规则",
    end: "pc",
    reason: "矩阵配置+策略预览",
    priority: "P2",
    group: "VR 双人策略矩阵规则",
    moduleCode: "VR",
    slug: "pc-vr-006",
  },
];
