import type { MatrixPrototypeSpec } from "./types";

export const SPECS: MatrixPrototypeSpec[] = [
  {
    storyId: "US-QL-001",
    title: "质量联系单类型与审批模板配置",
    end: "pc",
    reason: "模板配置+审批流设计",
    priority: "P3",
    group: "QL 质量联系单类型与审批模板配置",
    moduleCode: "QL",
    slug: "pc-ql-001",
  },
  {
    storyId: "US-QL-002",
    title: "创建质量联系单",
    end: "pda",
    reason: "PDA 触发+PC 补充",
    priority: "P3",
    group: "QL 创建质量联系单",
    moduleCode: "QL",
    slug: "pda-ql-002",
  },
  {
    storyId: "US-QL-002",
    title: "创建质量联系单",
    end: "pc",
    reason: "PDA 触发+PC 补充",
    priority: "P3",
    group: "QL 创建质量联系单",
    moduleCode: "QL",
    slug: "pc-ql-002",
  },
  {
    storyId: "US-QL-003",
    title: "质量联系单审批",
    end: "pc",
    reason: "审批流程+意见+驳回",
    priority: "P3",
    group: "QL 质量联系单审批",
    moduleCode: "QL",
    slug: "pc-ql-003",
  },
  {
    storyId: "US-QL-005",
    title: "质量联系单查询与统计",
    end: "pc",
    reason: "列表+统计+导出",
    priority: "P3",
    group: "QL 质量联系单查询与统计",
    moduleCode: "QL",
    slug: "pc-ql-005",
  },
  {
    storyId: "US-SA-001",
    title: "报损单管理",
    end: "pda",
    reason: "PDA 发起+PC 审批",
    priority: "P3",
    group: "SA 报损单管理",
    moduleCode: "SA",
    slug: "pda-sa-001",
  },
  {
    storyId: "US-SA-001",
    title: "报损单管理",
    end: "pc",
    reason: "PDA 发起+PC 审批",
    priority: "P3",
    group: "SA 报损单管理",
    moduleCode: "SA",
    slug: "pc-sa-001",
  },
  {
    storyId: "US-SA-002",
    title: "报溢单管理",
    end: "pda",
    reason: "PDA 发起+PC 审批",
    priority: "P3",
    group: "SA 报溢单管理",
    moduleCode: "SA",
    slug: "pda-sa-002",
  },
  {
    storyId: "US-SA-002",
    title: "报溢单管理",
    end: "pc",
    reason: "PDA 发起+PC 审批",
    priority: "P3",
    group: "SA 报溢单管理",
    moduleCode: "SA",
    slug: "pc-sa-002",
  },
  {
    storyId: "US-SA-003",
    title: "报损报溢查询与统计",
    end: "pc",
    reason: "列表+统计+导出",
    priority: "P3",
    group: "SA 报损报溢查询与统计",
    moduleCode: "SA",
    slug: "pc-sa-003",
  },
  {
    storyId: "US-RC-002",
    title: "差异处理",
    end: "pc",
    reason: "差异列表+处理流程",
    priority: "P3",
    group: "RC 差异处理",
    moduleCode: "RC",
    slug: "pc-rc-002",
  },
  {
    storyId: "US-RC-003",
    title: "手动触发对账",
    end: "pc",
    reason: "触发按钮+进度",
    priority: "P3",
    group: "RC 手动触发对账",
    moduleCode: "RC",
    slug: "pc-rc-003",
  },
  {
    storyId: "US-RC-004",
    title: "对账报表",
    end: "pc",
    reason: "对账结果+历史",
    priority: "P3",
    group: "RC 对账报表",
    moduleCode: "RC",
    slug: "pc-rc-004",
  },
  {
    storyId: "US-DI-001",
    title: "药检单平台对接配置",
    end: "pc",
    reason: "对接配置+测试连接",
    priority: "P3",
    group: "DI 药检单平台对接配置",
    moduleCode: "DI",
    slug: "pc-di-001",
  },
  {
    storyId: "US-DI-002",
    title: "扫码批量查询药检单",
    end: "pda",
    reason: "PDA 扫码查询",
    priority: "P3",
    group: "DI 扫码批量查询药检单",
    moduleCode: "DI",
    slug: "pda-di-002",
  },
  {
    storyId: "US-DI-003",
    title: "药检单存储与查看",
    end: "pc",
    reason: "药检单详情+PDF 预览",
    priority: "P3",
    group: "DI 药检单存储与查看",
    moduleCode: "DI",
    slug: "pc-di-003",
  },
  {
    storyId: "US-BA-001",
    title: "创建批号调整单",
    end: "pc",
    reason: "调整单表单+原因选择",
    priority: "P3",
    group: "BA 创建批号调整单",
    moduleCode: "BA",
    slug: "pc-ba-001",
  },
  {
    storyId: "US-BA-002",
    title: "批号调整双人审批",
    end: "pc",
    reason: "审批流程",
    priority: "P3",
    group: "BA 批号调整双人审批",
    moduleCode: "BA",
    slug: "pc-ba-002",
  },
  {
    storyId: "US-BA-003",
    title: "PDA 执行批号调整",
    end: "pda",
    reason: "PDA 实物核对+扫码",
    priority: "P3",
    group: "BA PDA 执行批号调整",
    moduleCode: "BA",
    slug: "pda-ba-003",
  },
  {
    storyId: "US-TC-001",
    title: "追溯码分类管理",
    end: "pc",
    reason: "分类配置+码规则",
    priority: "P1",
    group: "TC 追溯码分类管理",
    moduleCode: "TC",
    slug: "pc-tc-001",
  },
  {
    storyId: "US-TC-002",
    title: "码库管理（大中小码）",
    end: "pc",
    reason: "码库列表+层级关系",
    priority: "P1",
    group: "TC 码库管理",
    moduleCode: "TC",
    slug: "pc-tc-002",
  },
  {
    storyId: "US-TC-003",
    title: "追溯码与商品绑定",
    end: "pc",
    reason: "绑定关系管理",
    priority: "P1",
    group: "TC 追溯码与商品绑定",
    moduleCode: "TC",
    slug: "pc-tc-003",
  },
  {
    storyId: "US-TC-004",
    title: "PDA 追溯码对应关系维护",
    end: "pda",
    reason: "PDA 扫码建立关系",
    priority: "P1",
    group: "TC PDA 追溯码对应关系维护",
    moduleCode: "TC",
    slug: "pda-tc-004",
  },
  {
    storyId: "US-TC-006",
    title: "出库追溯码核验",
    end: "pda",
    reason: "扫码核验+差异提示",
    priority: "P1",
    group: "TC 出库追溯码核验",
    moduleCode: "TC",
    slug: "pda-tc-006",
  },
  {
    storyId: "US-TC-006",
    title: "出库追溯码核验",
    end: "pad",
    reason: "扫码核验+差异提示",
    priority: "P1",
    group: "TC 出库追溯码核验",
    moduleCode: "TC",
    slug: "pad-tc-006",
  },
  {
    storyId: "US-TC-007",
    title: "\"码上放心\"平台上报",
    end: "pc",
    reason: "上报状态+重试+日志",
    priority: "P1",
    group: "TC \"码上放心\"平台上报",
    moduleCode: "TC",
    slug: "pc-tc-007",
  },
  {
    storyId: "US-MPM-002",
    title: "映射规则配置",
    end: "pc",
    reason: "规则编辑器+条件",
    priority: "P1",
    group: "MPM 映射规则配置",
    moduleCode: "MPM",
    slug: "pc-mpm-002",
  },
  {
    storyId: "US-MPM-003",
    title: "待映射队列与质量联系单触发",
    end: "pc",
    reason: "队列列表+处理",
    priority: "P1",
    group: "MPM 待映射队列与质量联系单触发",
    moduleCode: "MPM",
    slug: "pc-mpm-003",
  },
  {
    storyId: "US-MPM-005",
    title: "反向追溯与映射溯源",
    end: "pc",
    reason: "追溯链路可视化",
    priority: "P1",
    group: "MPM 反向追溯与映射溯源",
    moduleCode: "MPM",
    slug: "pc-mpm-005",
  },
  {
    storyId: "US-MPM-006",
    title: "交易类型字典管理（PIX 三码）",
    end: "pc",
    reason: "字典+映射关系",
    priority: "P1",
    group: "MPM 交易类型字典管理",
    moduleCode: "MPM",
    slug: "pc-mpm-006",
  },
];
