import type { MatrixPrototypeSpec } from "./types";

export const SPECS: MatrixPrototypeSpec[] = [
  {
    storyId: "US-H1-001",
    title: "用户登录与 token 签发",
    end: "pc",
    reason: "登录页三角色入口",
    priority: "P0",
    group: "H1 用户登录与 token 签发",
    moduleCode: "H1",
    slug: "pc-h1-001",
  },
  {
    storyId: "US-H1-001",
    title: "用户登录与 token 签发",
    end: "pda",
    reason: "登录页三角色入口",
    priority: "P0",
    group: "H1 用户登录与 token 签发",
    moduleCode: "H1",
    slug: "pda-h1-001",
  },
  {
    storyId: "US-H1-002",
    title: "角色与权限管理",
    end: "pc",
    reason: "权限矩阵交互复杂",
    priority: "P0",
    group: "H1 角色与权限管理",
    moduleCode: "H1",
    slug: "pc-h1-002",
  },
  {
    storyId: "US-H1-005",
    title: "Token 失效与登出",
    end: "pc",
    reason: "登出交互+过期提示",
    priority: "P0",
    group: "H1 Token 失效与登出",
    moduleCode: "H1",
    slug: "pc-h1-005",
  },
  {
    storyId: "US-H1-005",
    title: "Token 失效与登出",
    end: "pda",
    reason: "登出交互+过期提示",
    priority: "P0",
    group: "H1 Token 失效与登出",
    moduleCode: "H1",
    slug: "pda-h1-005",
  },
  {
    storyId: "US-H1-006",
    title: "API Key 生命周期管理",
    end: "pc",
    reason: "密钥管理页",
    priority: "P0",
    group: "H1 API Key 生命周期管理",
    moduleCode: "H1",
    slug: "pc-h1-006",
  },
  {
    storyId: "US-H2-002",
    title: "审计追踪查询",
    end: "pc",
    reason: "查询界面+时间线展示",
    priority: "P0",
    group: "H2 审计追踪查询",
    moduleCode: "H2",
    slug: "pc-h2-002",
  },
  {
    storyId: "US-H2-004",
    title: "审计数据归档与保留",
    end: "pc",
    reason: "归档策略配置页",
    priority: "P0",
    group: "H2 审计数据归档与保留",
    moduleCode: "H2",
    slug: "pc-h2-004",
  },
  {
    storyId: "US-H2-006",
    title: "业务数据生命周期归档",
    end: "pc",
    reason: "归档规则+执行记录页",
    priority: "P0",
    group: "H2 业务数据生命周期归档",
    moduleCode: "H2",
    slug: "pc-h2-006",
  },
  {
    storyId: "US-H3-004",
    title: "API 文档可访问性",
    end: "pc",
    reason: "Swagger UI 定制页",
    priority: "P0",
    group: "H3 API 文档可访问性",
    moduleCode: "H3",
    slug: "pc-h3-004",
  },
  {
    storyId: "US-H4-001",
    title: "通知配置",
    end: "pc",
    reason: "通知模板+渠道配置",
    priority: "P2",
    group: "H4 通知配置",
    moduleCode: "H4",
    slug: "pc-h4-001",
  },
  {
    storyId: "US-H4-004",
    title: "通知发送记录查询",
    end: "pc",
    reason: "发送记录列表页",
    priority: "P2",
    group: "H4 通知发送记录查询",
    moduleCode: "H4",
    slug: "pc-h4-004",
  },
  {
    storyId: "US-H5-001",
    title: "快递商配置",
    end: "pc",
    reason: "快递商管理页",
    priority: "P2",
    group: "H5 快递商配置",
    moduleCode: "H5",
    slug: "pc-h5-001",
  },
  {
    storyId: "US-H5-002",
    title: "快递选择规则配置",
    end: "pc",
    reason: "规则配置表单",
    priority: "P2",
    group: "H5 快递选择规则配置",
    moduleCode: "H5",
    slug: "pc-h5-002",
  },
  {
    storyId: "US-H5-003",
    title: "快递单打印",
    end: "pc",
    reason: "打印预览+模板选择",
    priority: "P2",
    group: "H5 快递单打印",
    moduleCode: "H5",
    slug: "pc-h5-003",
  },
  {
    storyId: "US-H5-003",
    title: "快递单打印",
    end: "pad",
    reason: "打印预览+模板选择",
    priority: "P2",
    group: "H5 快递单打印",
    moduleCode: "H5",
    slug: "pad-h5-003",
  },
  {
    storyId: "US-H5-005",
    title: "快递轨迹查询",
    end: "pc",
    reason: "轨迹时间线（PC+门店可查）",
    priority: "P2",
    group: "H5 快递轨迹查询",
    moduleCode: "H5",
    slug: "pc-h5-005",
  },
  {
    storyId: "US-H5-005",
    title: "快递轨迹查询",
    end: "h5",
    reason: "轨迹时间线（PC+门店可查）",
    priority: "P2",
    group: "H5 快递轨迹查询",
    moduleCode: "H5",
    slug: "h5-h5-005",
  },
  {
    storyId: "US-AL-001",
    title: "告警定义注册",
    end: "pc",
    reason: "告警规则配置页",
    priority: "P2",
    group: "AL 告警定义注册",
    moduleCode: "AL",
    slug: "pc-al-001",
  },
  {
    storyId: "US-AL-003",
    title: "告警升级机制",
    end: "pc",
    reason: "升级策略配置",
    priority: "P2",
    group: "AL 告警升级机制",
    moduleCode: "AL",
    slug: "pc-al-003",
  },
  {
    storyId: "US-AL-004",
    title: "告警看板与统计",
    end: "pc",
    reason: "实时告警大屏",
    priority: "P2",
    group: "AL 告警看板与统计",
    moduleCode: "AL",
    slug: "pc-al-004",
  },
  {
    storyId: "US-AL-005",
    title: "告警通道与静默配置",
    end: "pc",
    reason: "通道+静默规则配置",
    priority: "P2",
    group: "AL 告警通道与静默配置",
    moduleCode: "AL",
    slug: "pc-al-005",
  },
  {
    storyId: "US-DOCK-001",
    title: "月台档案管理",
    end: "pc",
    reason: "月台CRUD+状态管理",
    priority: "P2",
    group: "DOCK 月台档案管理",
    moduleCode: "DOCK",
    slug: "pc-dock-001",
  },
  {
    storyId: "US-DOCK-002",
    title: "预约创建",
    end: "pc",
    reason: "预约表单+时间窗选择",
    priority: "P2",
    group: "DOCK 预约创建",
    moduleCode: "DOCK",
    slug: "pc-dock-002",
  },
  {
    storyId: "US-DOCK-002",
    title: "预约创建",
    end: "pda",
    reason: "预约表单+时间窗选择",
    priority: "P2",
    group: "DOCK 预约创建",
    moduleCode: "DOCK",
    slug: "pda-dock-002",
  },
  {
    storyId: "US-DOCK-003",
    title: "预约时间窗冲突检测",
    end: "pc",
    reason: "甘特图式冲突可视化",
    priority: "P2",
    group: "DOCK 预约时间窗冲突检测",
    moduleCode: "DOCK",
    slug: "pc-dock-003",
  },
  {
    storyId: "US-DOCK-004",
    title: "预约变更与取消",
    end: "pc",
    reason: "变更流程+审批",
    priority: "P2",
    group: "DOCK 预约变更与取消",
    moduleCode: "DOCK",
    slug: "pc-dock-004",
  },
  {
    storyId: "US-DOCK-005",
    title: "实到对账",
    end: "pda",
    reason: "PDA 扫码对账",
    priority: "P2",
    group: "DOCK 实到对账",
    moduleCode: "DOCK",
    slug: "pda-dock-005",
  },
  {
    storyId: "US-DOCK-006",
    title: "月台占用看板",
    end: "pc",
    reason: "实时占用大屏",
    priority: "P2",
    group: "DOCK 月台占用看板",
    moduleCode: "DOCK",
    slug: "pc-dock-006",
  },
  {
    storyId: "US-DOCK-006",
    title: "月台占用看板",
    end: "pad",
    reason: "实时占用大屏",
    priority: "P2",
    group: "DOCK 月台占用看板",
    moduleCode: "DOCK",
    slug: "pad-dock-006",
  },
  {
    storyId: "US-DOCK-007",
    title: "预约统计与报表",
    end: "pc",
    reason: "报表页",
    priority: "P2",
    group: "DOCK 预约统计与报表",
    moduleCode: "DOCK",
    slug: "pc-dock-007",
  },
  {
    storyId: "US-DR-001",
    title: "司机端登录与今日任务列表",
    end: "h5",
    reason: "司机移动端首页",
    priority: "P3",
    group: "DR 司机端登录与今日任务列表",
    moduleCode: "DR",
    slug: "h5-dr-001",
  },
  {
    storyId: "US-DR-002",
    title: "司机签收（自有车队交接确认）",
    end: "h5",
    reason: "扫码+签字+拍照",
    priority: "P3",
    group: "DR 司机签收",
    moduleCode: "DR",
    slug: "h5-dr-002",
  },
  {
    storyId: "US-DR-003",
    title: "在途异常上报",
    end: "h5",
    reason: "异常类型选择+拍照+定位",
    priority: "P3",
    group: "DR 在途异常上报",
    moduleCode: "DR",
    slug: "h5-dr-003",
  },
  {
    storyId: "US-DR-004",
    title: "司机端到店签收（客户签字）",
    end: "h5",
    reason: "客户手写签字+拍照",
    priority: "P3",
    group: "DR 司机端到店签收",
    moduleCode: "DR",
    slug: "h5-dr-004",
  },
  {
    storyId: "US-DR-005",
    title: "司机端工作日志与绩效查询",
    end: "h5",
    reason: "日志列表+绩效统计",
    priority: "P3",
    group: "DR 司机端工作日志与绩效查询",
    moduleCode: "DR",
    slug: "h5-dr-005",
  },
  {
    storyId: "US-ST-001",
    title: "门店登录与首页",
    end: "pc",
    reason: "门店端首页+快捷入口",
    priority: "P3",
    group: "ST 门店登录与首页",
    moduleCode: "ST",
    slug: "pc-st-001",
  },
  {
    storyId: "US-ST-001",
    title: "门店登录与首页",
    end: "pad",
    reason: "门店端首页+快捷入口",
    priority: "P3",
    group: "ST 门店登录与首页",
    moduleCode: "ST",
    slug: "pad-st-001",
  },
  {
    storyId: "US-ST-002",
    title: "门店订货与补货请求",
    end: "pc",
    reason: "商品目录+购物车+下单",
    priority: "P3",
    group: "ST 门店订货与补货请求",
    moduleCode: "ST",
    slug: "pc-st-002",
  },
  {
    storyId: "US-ST-002",
    title: "门店订货与补货请求",
    end: "pad",
    reason: "商品目录+购物车+下单",
    priority: "P3",
    group: "ST 门店订货与补货请求",
    moduleCode: "ST",
    slug: "pad-st-002",
  },
  {
    storyId: "US-ST-003",
    title: "门店签收（电子签收）",
    end: "pc",
    reason: "扫码签收+温控确认",
    priority: "P3",
    group: "ST 门店签收",
    moduleCode: "ST",
    slug: "pc-st-003",
  },
  {
    storyId: "US-ST-003",
    title: "门店签收（电子签收）",
    end: "pad",
    reason: "扫码签收+温控确认",
    priority: "P3",
    group: "ST 门店签收",
    moduleCode: "ST",
    slug: "pad-st-003",
  },
  {
    storyId: "US-ST-004",
    title: "门店退货发起",
    end: "pc",
    reason: "退货申请表单",
    priority: "P3",
    group: "ST 门店退货发起",
    moduleCode: "ST",
    slug: "pc-st-004",
  },
  {
    storyId: "US-ST-004",
    title: "门店退货发起",
    end: "pad",
    reason: "退货申请表单",
    priority: "P3",
    group: "ST 门店退货发起",
    moduleCode: "ST",
    slug: "pad-st-004",
  },
  {
    storyId: "US-ST-005",
    title: "门店订单查询与历史",
    end: "pc",
    reason: "订单列表+详情+筛选",
    priority: "P3",
    group: "ST 门店订单查询与历史",
    moduleCode: "ST",
    slug: "pc-st-005",
  },
  {
    storyId: "US-ST-005",
    title: "门店订单查询与历史",
    end: "pad",
    reason: "订单列表+详情+筛选",
    priority: "P3",
    group: "ST 门店订单查询与历史",
    moduleCode: "ST",
    slug: "pad-st-005",
  },
  {
    storyId: "US-ST-006",
    title: "门店冷链订单温控查询",
    end: "pc",
    reason: "温度曲线+超标标记",
    priority: "P3",
    group: "ST 门店冷链订单温控查询",
    moduleCode: "ST",
    slug: "pc-st-006",
  },
  {
    storyId: "US-ST-006",
    title: "门店冷链订单温控查询",
    end: "pad",
    reason: "温度曲线+超标标记",
    priority: "P3",
    group: "ST 门店冷链订单温控查询",
    moduleCode: "ST",
    slug: "pad-st-006",
  },
  {
    storyId: "US-M1-001",
    title: "商品档案管理",
    end: "pc",
    reason: "商品详情页字段多+资质附件",
    priority: "P1",
    group: "M1 商品档案管理",
    moduleCode: "M1",
    slug: "pc-m1-001",
  },
  {
    storyId: "US-M1-002",
    title: "供应商资质档案",
    end: "pc",
    reason: "资质有效期+证照管理",
    priority: "P1",
    group: "M1 供应商资质档案",
    moduleCode: "M1",
    slug: "pc-m1-002",
  },
  {
    storyId: "US-M1-003",
    title: "客户/门店档案",
    end: "pc",
    reason: "客户+门店层级管理",
    priority: "P1",
    group: "M1 客户/门店档案",
    moduleCode: "M1",
    slug: "pc-m1-003",
  },
  {
    storyId: "US-M1-004",
    title: "仓库与库位管理",
    end: "pc",
    reason: "库位可视化+温区标记",
    priority: "P1",
    group: "M1 仓库与库位管理",
    moduleCode: "M1",
    slug: "pc-m1-004",
  },
  {
    storyId: "US-M1-004a",
    title: "容器（LPN）管理",
    end: "pc",
    reason: "LPN 绑定/解绑+PDA 扫码",
    priority: "P1",
    group: "M1 容器",
    moduleCode: "M1",
    slug: "pc-m1-004a",
  },
  {
    storyId: "US-M1-004a",
    title: "容器（LPN）管理",
    end: "pda",
    reason: "LPN 绑定/解绑+PDA 扫码",
    priority: "P1",
    group: "M1 容器",
    moduleCode: "M1",
    slug: "pda-m1-004a",
  },
  {
    storyId: "US-M1-006",
    title: "用户与权限管理",
    end: "pc",
    reason: "用户+角色+权限矩阵（建议与 H1-002 合并为 1 个原型）",
    priority: "P1",
    group: "M1 用户与权限管理",
    moduleCode: "M1",
    slug: "pc-m1-006",
  },
  {
    storyId: "US-M1-007",
    title: "多货主架构",
    end: "pc",
    reason: "货主切换+数据隔离可视化",
    priority: "P1",
    group: "M1 多货主架构",
    moduleCode: "M1",
    slug: "pc-m1-007",
  },
  {
    storyId: "US-M1-008",
    title: "系统配置中心",
    end: "pc",
    reason: "配置项分组+搜索+变更历史",
    priority: "P1",
    group: "M1 系统配置中心",
    moduleCode: "M1",
    slug: "pc-m1-008",
  },
  {
    storyId: "US-M1-009",
    title: "多仓管理",
    end: "pc",
    reason: "仓库列表+切换+权限",
    priority: "P1",
    group: "M1 多仓管理",
    moduleCode: "M1",
    slug: "pc-m1-009",
  },
  {
    storyId: "US-M1-010",
    title: "特殊药品分类字典管理",
    end: "pc",
    reason: "分类树+规则绑定",
    priority: "P1",
    group: "M1 特殊药品分类字典管理",
    moduleCode: "M1",
    slug: "pc-m1-010",
  },
  {
    storyId: "US-M2-001",
    title: "创建 ASN（采购入库通知）",
    end: "pc",
    reason: "ASN 表单+ERP 推送状态",
    priority: "P1",
    group: "M2 创建 ASN",
    moduleCode: "M2",
    slug: "pc-m2-001",
  },
  {
    storyId: "US-M2-002",
    title: "PDA/PC Web 收货（到货签收）",
    end: "pda",
    reason: "PDA 扫码收货+月台对接",
    priority: "P1",
    group: "M2 PDA/PC Web 收货",
    moduleCode: "M2",
    slug: "pda-m2-002",
  },
  {
    storyId: "US-M2-002",
    title: "PDA/PC Web 收货（到货签收）",
    end: "pc",
    reason: "PC Web USB 扫码枪+手工收货",
    priority: "P1",
    group: "M2 PDA/PC Web 收货",
    moduleCode: "M2",
    slug: "pc-m2-002",
  },
  {
    storyId: "US-M2-003",
    title: "PDA/PC Web 验收",
    end: "pda",
    reason: "14项验收+离线+档案补录子流程",
    priority: "P1",
    group: "M2 PDA/PC Web 验收",
    moduleCode: "M2",
    slug: "pda-m2-003",
  },
  {
    storyId: "US-M2-003",
    title: "PDA/PC Web 验收",
    end: "pc",
    reason: "PC Web USB 扫码枪+手工验收",
    priority: "P1",
    group: "M2 PDA/PC Web 验收",
    moduleCode: "M2",
    slug: "pc-m2-003",
  },
  {
    storyId: "US-M2-004",
    title: "双人验收签字",
    end: "pda",
    reason: "三档策略动态切换",
    priority: "P1",
    group: "M2 双人验收签字",
    moduleCode: "M2",
    slug: "pda-m2-004",
  },
  {
    storyId: "US-M2-005",
    title: "PDA/PC Web 智能上架",
    end: "pda",
    reason: "库位推荐+扫码确认",
    priority: "P1",
    group: "M2 PDA/PC Web 智能上架",
    moduleCode: "M2",
    slug: "pda-m2-005",
  },
  {
    storyId: "US-M2-005",
    title: "PDA/PC Web 智能上架",
    end: "pc",
    reason: "PC Web 库位推荐+扫码枪/手工确认",
    priority: "P1",
    group: "M2 PDA/PC Web 智能上架",
    moduleCode: "M2",
    slug: "pc-m2-005",
  },
  {
    storyId: "US-M2-006",
    title: "收货异常处理",
    end: "pda",
    reason: "异常类型+处理流程",
    priority: "P1",
    group: "M2 收货异常处理",
    moduleCode: "M2",
    slug: "pda-m2-006",
  },
  {
    storyId: "US-M2-006",
    title: "收货异常处理",
    end: "pc",
    reason: "异常类型+处理流程",
    priority: "P1",
    group: "M2 收货异常处理",
    moduleCode: "M2",
    slug: "pc-m2-006",
  },
  {
    storyId: "US-M2-007",
    title: "收货单据打印",
    end: "pc",
    reason: "打印预览+模板",
    priority: "P1",
    group: "M2 收货单据打印",
    moduleCode: "M2",
    slug: "pc-m2-007",
  },
  {
    storyId: "US-M2-007",
    title: "收货单据打印",
    end: "pad",
    reason: "打印预览+模板",
    priority: "P1",
    group: "M2 收货单据打印",
    moduleCode: "M2",
    slug: "pad-m2-007",
  },
  {
    storyId: "US-M2-008",
    title: "收货进度看板",
    end: "pc",
    reason: "实时进度大屏",
    priority: "P1",
    group: "M2 收货进度看板",
    moduleCode: "M2",
    slug: "pc-m2-008",
  },
  {
    storyId: "US-M2-008",
    title: "收货进度看板",
    end: "pad",
    reason: "实时进度大屏",
    priority: "P1",
    group: "M2 收货进度看板",
    moduleCode: "M2",
    slug: "pad-m2-008",
  },
  {
    storyId: "US-M2-009",
    title: "打印模板设计模块",
    end: "pc",
    reason: "模板编辑器（拖拽式，极复杂交互）",
    priority: "P1",
    group: "M2 打印模板设计模块",
    moduleCode: "M2",
    slug: "pc-m2-009",
  },
  {
    storyId: "US-M2-010",
    title: "上架策略配置",
    end: "pc",
    reason: "策略规则配置",
    priority: "P1",
    group: "M2 上架策略配置",
    moduleCode: "M2",
    slug: "pc-m2-010",
  },
];
