import type { MatrixPrototypeSpec } from "./types";

export const FULL_MATRIX_SPECS: MatrixPrototypeSpec[] = [
  {
    storyId: "US-H1-001",
    title: "用户登录与 token 签发",
    end: "pc",
    reason: "登录页三角色入口",
    priority: "P0",
    group: "H1 用户登录与 token 签发",
    moduleCode: "H1",
    slug: "pc-h1-001",
  },
  {
    storyId: "US-H1-001",
    title: "用户登录与 token 签发",
    end: "pda",
    reason: "登录页三角色入口",
    priority: "P0",
    group: "H1 用户登录与 token 签发",
    moduleCode: "H1",
    slug: "pda-h1-001",
  },
  {
    storyId: "US-H1-002",
    title: "角色与权限管理",
    end: "pc",
    reason: "权限矩阵交互复杂",
    priority: "P0",
    group: "H1 角色与权限管理",
    moduleCode: "H1",
    slug: "pc-h1-002",
  },
  {
    storyId: "US-H1-005",
    title: "Token 失效与登出",
    end: "pc",
    reason: "登出交互+过期提示",
    priority: "P0",
    group: "H1 Token 失效与登出",
    moduleCode: "H1",
    slug: "pc-h1-005",
  },
  {
    storyId: "US-H1-005",
    title: "Token 失效与登出",
    end: "pda",
    reason: "登出交互+过期提示",
    priority: "P0",
    group: "H1 Token 失效与登出",
    moduleCode: "H1",
    slug: "pda-h1-005",
  },
  {
    storyId: "US-H1-006",
    title: "API Key 生命周期管理",
    end: "pc",
    reason: "密钥管理页",
    priority: "P0",
    group: "H1 API Key 生命周期管理",
    moduleCode: "H1",
    slug: "pc-h1-006",
  },
  {
    storyId: "US-H2-002",
    title: "审计追踪查询",
    end: "pc",
    reason: "查询界面+时间线展示",
    priority: "P0",
    group: "H2 审计追踪查询",
    moduleCode: "H2",
    slug: "pc-h2-002",
  },
  {
    storyId: "US-H2-004",
    title: "审计数据归档与保留",
    end: "pc",
    reason: "归档策略配置页",
    priority: "P0",
    group: "H2 审计数据归档与保留",
    moduleCode: "H2",
    slug: "pc-h2-004",
  },
  {
    storyId: "US-H2-006",
    title: "业务数据生命周期归档",
    end: "pc",
    reason: "归档规则+执行记录页",
    priority: "P0",
    group: "H2 业务数据生命周期归档",
    moduleCode: "H2",
    slug: "pc-h2-006",
  },
  {
    storyId: "US-H3-004",
    title: "API 文档可访问性",
    end: "pc",
    reason: "Swagger UI 定制页",
    priority: "P0",
    group: "H3 API 文档可访问性",
    moduleCode: "H3",
    slug: "pc-h3-004",
  },
  {
    storyId: "US-H4-001",
    title: "通知配置",
    end: "pc",
    reason: "通知模板+渠道配置",
    priority: "P2",
    group: "H4 通知配置",
    moduleCode: "H4",
    slug: "pc-h4-001",
  },
  {
    storyId: "US-H4-004",
    title: "通知发送记录查询",
    end: "pc",
    reason: "发送记录列表页",
    priority: "P2",
    group: "H4 通知发送记录查询",
    moduleCode: "H4",
    slug: "pc-h4-004",
  },
  {
    storyId: "US-H5-001",
    title: "快递商配置",
    end: "pc",
    reason: "快递商管理页",
    priority: "P2",
    group: "H5 快递商配置",
    moduleCode: "H5",
    slug: "pc-h5-001",
  },
  {
    storyId: "US-H5-002",
    title: "快递选择规则配置",
    end: "pc",
    reason: "规则配置表单",
    priority: "P2",
    group: "H5 快递选择规则配置",
    moduleCode: "H5",
    slug: "pc-h5-002",
  },
  {
    storyId: "US-H5-003",
    title: "快递单打印",
    end: "pc",
    reason: "打印预览+模板选择",
    priority: "P2",
    group: "H5 快递单打印",
    moduleCode: "H5",
    slug: "pc-h5-003",
  },
  {
    storyId: "US-H5-003",
    title: "快递单打印",
    end: "pad",
    reason: "打印预览+模板选择",
    priority: "P2",
    group: "H5 快递单打印",
    moduleCode: "H5",
    slug: "pad-h5-003",
  },
  {
    storyId: "US-H5-005",
    title: "快递轨迹查询",
    end: "pc",
    reason: "轨迹时间线（PC+门店可查）",
    priority: "P2",
    group: "H5 快递轨迹查询",
    moduleCode: "H5",
    slug: "pc-h5-005",
  },
  {
    storyId: "US-H5-005",
    title: "快递轨迹查询",
    end: "h5",
    reason: "轨迹时间线（PC+门店可查）",
    priority: "P2",
    group: "H5 快递轨迹查询",
    moduleCode: "H5",
    slug: "h5-h5-005",
  },
  {
    storyId: "US-AL-001",
    title: "告警定义注册",
    end: "pc",
    reason: "告警规则配置页",
    priority: "P2",
    group: "AL 告警定义注册",
    moduleCode: "AL",
    slug: "pc-al-001",
  },
  {
    storyId: "US-AL-003",
    title: "告警升级机制",
    end: "pc",
    reason: "升级策略配置",
    priority: "P2",
    group: "AL 告警升级机制",
    moduleCode: "AL",
    slug: "pc-al-003",
  },
  {
    storyId: "US-AL-004",
    title: "告警看板与统计",
    end: "pc",
    reason: "实时告警大屏",
    priority: "P2",
    group: "AL 告警看板与统计",
    moduleCode: "AL",
    slug: "pc-al-004",
  },
  {
    storyId: "US-AL-005",
    title: "告警通道与静默配置",
    end: "pc",
    reason: "通道+静默规则配置",
    priority: "P2",
    group: "AL 告警通道与静默配置",
    moduleCode: "AL",
    slug: "pc-al-005",
  },
  {
    storyId: "US-DOCK-001",
    title: "月台档案管理",
    end: "pc",
    reason: "月台CRUD+状态管理",
    priority: "P2",
    group: "DOCK 月台档案管理",
    moduleCode: "DOCK",
    slug: "pc-dock-001",
  },
  {
    storyId: "US-DOCK-002",
    title: "预约创建",
    end: "pc",
    reason: "预约表单+时间窗选择",
    priority: "P2",
    group: "DOCK 预约创建",
    moduleCode: "DOCK",
    slug: "pc-dock-002",
  },
  {
    storyId: "US-DOCK-002",
    title: "预约创建",
    end: "pda",
    reason: "预约表单+时间窗选择",
    priority: "P2",
    group: "DOCK 预约创建",
    moduleCode: "DOCK",
    slug: "pda-dock-002",
  },
  {
    storyId: "US-DOCK-003",
    title: "预约时间窗冲突检测",
    end: "pc",
    reason: "甘特图式冲突可视化",
    priority: "P2",
    group: "DOCK 预约时间窗冲突检测",
    moduleCode: "DOCK",
    slug: "pc-dock-003",
  },
  {
    storyId: "US-DOCK-004",
    title: "预约变更与取消",
    end: "pc",
    reason: "变更流程+审批",
    priority: "P2",
    group: "DOCK 预约变更与取消",
    moduleCode: "DOCK",
    slug: "pc-dock-004",
  },
  {
    storyId: "US-DOCK-005",
    title: "实到对账",
    end: "pda",
    reason: "PDA 扫码对账",
    priority: "P2",
    group: "DOCK 实到对账",
    moduleCode: "DOCK",
    slug: "pda-dock-005",
  },
  {
    storyId: "US-DOCK-006",
    title: "月台占用看板",
    end: "pc",
    reason: "实时占用大屏",
    priority: "P2",
    group: "DOCK 月台占用看板",
    moduleCode: "DOCK",
    slug: "pc-dock-006",
  },
  {
    storyId: "US-DOCK-006",
    title: "月台占用看板",
    end: "pad",
    reason: "实时占用大屏",
    priority: "P2",
    group: "DOCK 月台占用看板",
    moduleCode: "DOCK",
    slug: "pad-dock-006",
  },
  {
    storyId: "US-DOCK-007",
    title: "预约统计与报表",
    end: "pc",
    reason: "报表页",
    priority: "P2",
    group: "DOCK 预约统计与报表",
    moduleCode: "DOCK",
    slug: "pc-dock-007",
  },
  {
    storyId: "US-DR-001",
    title: "司机端登录与今日任务列表",
    end: "h5",
    reason: "司机移动端首页",
    priority: "P3",
    group: "DR 司机端登录与今日任务列表",
    moduleCode: "DR",
    slug: "h5-dr-001",
  },
  {
    storyId: "US-DR-002",
    title: "司机签收（自有车队交接确认）",
    end: "h5",
    reason: "扫码+签字+拍照",
    priority: "P3",
    group: "DR 司机签收",
    moduleCode: "DR",
    slug: "h5-dr-002",
  },
  {
    storyId: "US-DR-003",
    title: "在途异常上报",
    end: "h5",
    reason: "异常类型选择+拍照+定位",
    priority: "P3",
    group: "DR 在途异常上报",
    moduleCode: "DR",
    slug: "h5-dr-003",
  },
  {
    storyId: "US-DR-004",
    title: "司机端到店签收（客户签字）",
    end: "h5",
    reason: "客户手写签字+拍照",
    priority: "P3",
    group: "DR 司机端到店签收",
    moduleCode: "DR",
    slug: "h5-dr-004",
  },
  {
    storyId: "US-DR-005",
    title: "司机端工作日志与绩效查询",
    end: "h5",
    reason: "日志列表+绩效统计",
    priority: "P3",
    group: "DR 司机端工作日志与绩效查询",
    moduleCode: "DR",
    slug: "h5-dr-005",
  },
  {
    storyId: "US-ST-001",
    title: "门店登录与首页",
    end: "pc",
    reason: "门店端首页+快捷入口",
    priority: "P3",
    group: "ST 门店登录与首页",
    moduleCode: "ST",
    slug: "pc-st-001",
  },
  {
    storyId: "US-ST-001",
    title: "门店登录与首页",
    end: "pad",
    reason: "门店端首页+快捷入口",
    priority: "P3",
    group: "ST 门店登录与首页",
    moduleCode: "ST",
    slug: "pad-st-001",
  },
  {
    storyId: "US-ST-002",
    title: "门店订货与补货请求",
    end: "pc",
    reason: "商品目录+购物车+下单",
    priority: "P3",
    group: "ST 门店订货与补货请求",
    moduleCode: "ST",
    slug: "pc-st-002",
  },
  {
    storyId: "US-ST-002",
    title: "门店订货与补货请求",
    end: "pad",
    reason: "商品目录+购物车+下单",
    priority: "P3",
    group: "ST 门店订货与补货请求",
    moduleCode: "ST",
    slug: "pad-st-002",
  },
  {
    storyId: "US-ST-003",
    title: "门店签收（电子签收）",
    end: "pc",
    reason: "扫码签收+温控确认",
    priority: "P3",
    group: "ST 门店签收",
    moduleCode: "ST",
    slug: "pc-st-003",
  },
  {
    storyId: "US-ST-003",
    title: "门店签收（电子签收）",
    end: "pad",
    reason: "扫码签收+温控确认",
    priority: "P3",
    group: "ST 门店签收",
    moduleCode: "ST",
    slug: "pad-st-003",
  },
  {
    storyId: "US-ST-004",
    title: "门店退货发起",
    end: "pc",
    reason: "退货申请表单",
    priority: "P3",
    group: "ST 门店退货发起",
    moduleCode: "ST",
    slug: "pc-st-004",
  },
  {
    storyId: "US-ST-004",
    title: "门店退货发起",
    end: "pad",
    reason: "退货申请表单",
    priority: "P3",
    group: "ST 门店退货发起",
    moduleCode: "ST",
    slug: "pad-st-004",
  },
  {
    storyId: "US-ST-005",
    title: "门店订单查询与历史",
    end: "pc",
    reason: "订单列表+详情+筛选",
    priority: "P3",
    group: "ST 门店订单查询与历史",
    moduleCode: "ST",
    slug: "pc-st-005",
  },
  {
    storyId: "US-ST-005",
    title: "门店订单查询与历史",
    end: "pad",
    reason: "订单列表+详情+筛选",
    priority: "P3",
    group: "ST 门店订单查询与历史",
    moduleCode: "ST",
    slug: "pad-st-005",
  },
  {
    storyId: "US-ST-006",
    title: "门店冷链订单温控查询",
    end: "pc",
    reason: "温度曲线+超标标记",
    priority: "P3",
    group: "ST 门店冷链订单温控查询",
    moduleCode: "ST",
    slug: "pc-st-006",
  },
  {
    storyId: "US-ST-006",
    title: "门店冷链订单温控查询",
    end: "pad",
    reason: "温度曲线+超标标记",
    priority: "P3",
    group: "ST 门店冷链订单温控查询",
    moduleCode: "ST",
    slug: "pad-st-006",
  },
  {
    storyId: "US-M1-001",
    title: "商品档案管理",
    end: "pc",
    reason: "商品详情页字段多+资质附件",
    priority: "P1",
    group: "M1 商品档案管理",
    moduleCode: "M1",
    slug: "pc-m1-001",
  },
  {
    storyId: "US-M1-002",
    title: "供应商资质档案",
    end: "pc",
    reason: "资质有效期+证照管理",
    priority: "P1",
    group: "M1 供应商资质档案",
    moduleCode: "M1",
    slug: "pc-m1-002",
  },
  {
    storyId: "US-M1-003",
    title: "客户/门店档案",
    end: "pc",
    reason: "客户+门店层级管理",
    priority: "P1",
    group: "M1 客户/门店档案",
    moduleCode: "M1",
    slug: "pc-m1-003",
  },
  {
    storyId: "US-M1-004",
    title: "仓库与库位管理",
    end: "pc",
    reason: "库位可视化+温区标记",
    priority: "P1",
    group: "M1 仓库与库位管理",
    moduleCode: "M1",
    slug: "pc-m1-004",
  },
  {
    storyId: "US-M1-004a",
    title: "容器（LPN）管理",
    end: "pc",
    reason: "LPN 绑定/解绑+PDA 扫码",
    priority: "P1",
    group: "M1 容器",
    moduleCode: "M1",
    slug: "pc-m1-004a",
  },
  {
    storyId: "US-M1-004a",
    title: "容器（LPN）管理",
    end: "pda",
    reason: "LPN 绑定/解绑+PDA 扫码",
    priority: "P1",
    group: "M1 容器",
    moduleCode: "M1",
    slug: "pda-m1-004a",
  },
  {
    storyId: "US-M1-006",
    title: "用户与权限管理",
    end: "pc",
    reason: "用户+角色+权限矩阵（建议与 H1-002 合并为 1 个原型）",
    priority: "P1",
    group: "M1 用户与权限管理",
    moduleCode: "M1",
    slug: "pc-m1-006",
  },
  {
    storyId: "US-M1-007",
    title: "多货主架构",
    end: "pc",
    reason: "货主切换+数据隔离可视化",
    priority: "P1",
    group: "M1 多货主架构",
    moduleCode: "M1",
    slug: "pc-m1-007",
  },
  {
    storyId: "US-M1-008",
    title: "系统配置中心",
    end: "pc",
    reason: "配置项分组+搜索+变更历史",
    priority: "P1",
    group: "M1 系统配置中心",
    moduleCode: "M1",
    slug: "pc-m1-008",
  },
  {
    storyId: "US-M1-009",
    title: "多仓管理",
    end: "pc",
    reason: "仓库列表+切换+权限",
    priority: "P1",
    group: "M1 多仓管理",
    moduleCode: "M1",
    slug: "pc-m1-009",
  },
  {
    storyId: "US-M1-010",
    title: "特殊药品分类字典管理",
    end: "pc",
    reason: "分类树+规则绑定",
    priority: "P1",
    group: "M1 特殊药品分类字典管理",
    moduleCode: "M1",
    slug: "pc-m1-010",
  },
  {
    storyId: "US-M2-001",
    title: "创建 ASN（采购入库通知）",
    end: "pc",
    reason: "ASN 表单+ERP 推送状态",
    priority: "P1",
    group: "M2 创建 ASN",
    moduleCode: "M2",
    slug: "pc-m2-001",
  },
  {
    storyId: "US-M2-002",
    title: "PDA/PC Web 收货（到货签收）",
    end: "pda",
    reason: "PDA 扫码收货+月台对接",
    priority: "P1",
    group: "M2 PDA/PC Web 收货",
    moduleCode: "M2",
    slug: "pda-m2-002",
  },
  {
    storyId: "US-M2-002",
    title: "PDA/PC Web 收货（到货签收）",
    end: "pc",
    reason: "PC Web USB 扫码枪+手工收货",
    priority: "P1",
    group: "M2 PDA/PC Web 收货",
    moduleCode: "M2",
    slug: "pc-m2-002",
  },
  {
    storyId: "US-M2-003",
    title: "PDA/PC Web 验收",
    end: "pda",
    reason: "14项验收+离线+档案补录子流程",
    priority: "P1",
    group: "M2 PDA/PC Web 验收",
    moduleCode: "M2",
    slug: "pda-m2-003",
  },
  {
    storyId: "US-M2-003",
    title: "PDA/PC Web 验收",
    end: "pc",
    reason: "PC Web USB 扫码枪+手工验收",
    priority: "P1",
    group: "M2 PDA/PC Web 验收",
    moduleCode: "M2",
    slug: "pc-m2-003",
  },
  {
    storyId: "US-M2-004",
    title: "双人验收签字",
    end: "pda",
    reason: "三档策略动态切换",
    priority: "P1",
    group: "M2 双人验收签字",
    moduleCode: "M2",
    slug: "pda-m2-004",
  },
  {
    storyId: "US-M2-005",
    title: "PDA/PC Web 智能上架",
    end: "pda",
    reason: "库位推荐+扫码确认",
    priority: "P1",
    group: "M2 PDA/PC Web 智能上架",
    moduleCode: "M2",
    slug: "pda-m2-005",
  },
  {
    storyId: "US-M2-005",
    title: "PDA/PC Web 智能上架",
    end: "pc",
    reason: "PC Web 库位推荐+扫码枪/手工确认",
    priority: "P1",
    group: "M2 PDA/PC Web 智能上架",
    moduleCode: "M2",
    slug: "pc-m2-005",
  },
  {
    storyId: "US-M2-006",
    title: "收货异常处理",
    end: "pda",
    reason: "异常类型+处理流程",
    priority: "P1",
    group: "M2 收货异常处理",
    moduleCode: "M2",
    slug: "pda-m2-006",
  },
  {
    storyId: "US-M2-006",
    title: "收货异常处理",
    end: "pc",
    reason: "异常类型+处理流程",
    priority: "P1",
    group: "M2 收货异常处理",
    moduleCode: "M2",
    slug: "pc-m2-006",
  },
  {
    storyId: "US-M2-007",
    title: "收货单据打印",
    end: "pc",
    reason: "打印预览+模板",
    priority: "P1",
    group: "M2 收货单据打印",
    moduleCode: "M2",
    slug: "pc-m2-007",
  },
  {
    storyId: "US-M2-007",
    title: "收货单据打印",
    end: "pad",
    reason: "打印预览+模板",
    priority: "P1",
    group: "M2 收货单据打印",
    moduleCode: "M2",
    slug: "pad-m2-007",
  },
  {
    storyId: "US-M2-008",
    title: "收货进度看板",
    end: "pc",
    reason: "实时进度大屏",
    priority: "P1",
    group: "M2 收货进度看板",
    moduleCode: "M2",
    slug: "pc-m2-008",
  },
  {
    storyId: "US-M2-008",
    title: "收货进度看板",
    end: "pad",
    reason: "实时进度大屏",
    priority: "P1",
    group: "M2 收货进度看板",
    moduleCode: "M2",
    slug: "pad-m2-008",
  },
  {
    storyId: "US-M2-009",
    title: "打印模板设计模块",
    end: "pc",
    reason: "模板编辑器（拖拽式，极复杂交互）",
    priority: "P1",
    group: "M2 打印模板设计模块",
    moduleCode: "M2",
    slug: "pc-m2-009",
  },
  {
    storyId: "US-M2-010",
    title: "上架策略配置",
    end: "pc",
    reason: "策略规则配置",
    priority: "P1",
    group: "M2 上架策略配置",
    moduleCode: "M2",
    slug: "pc-m2-010",
  },
  {
    storyId: "US-M3-001",
    title: "实时库存查询",
    end: "pc",
    reason: "多维筛选+批次展开",
    priority: "P2",
    group: "M3 实时库存查询",
    moduleCode: "M3",
    slug: "pc-m3-001",
  },
  {
    storyId: "US-M3-002",
    title: "批次与效期管理",
    end: "pc",
    reason: "批次列表+近效期预警",
    priority: "P2",
    group: "M3 批次与效期管理",
    moduleCode: "M3",
    slug: "pc-m3-002",
  },
  {
    storyId: "US-M3-003",
    title: "库存状态管理",
    end: "pc",
    reason: "状态流转+隔离/解隔离",
    priority: "P2",
    group: "M3 库存状态管理",
    moduleCode: "M3",
    slug: "pc-m3-003",
  },
  {
    storyId: "US-M3-004",
    title: "在库养护",
    end: "pda",
    reason: "PDA 养护记录+PC 计划",
    priority: "P2",
    group: "M3 在库养护",
    moduleCode: "M3",
    slug: "pda-m3-004",
  },
  {
    storyId: "US-M3-004",
    title: "在库养护",
    end: "pc",
    reason: "PDA 养护记录+PC 计划",
    priority: "P2",
    group: "M3 在库养护",
    moduleCode: "M3",
    slug: "pc-m3-004",
  },
  {
    storyId: "US-M3-005",
    title: "库存盘点",
    end: "pda",
    reason: "PDA 盘点扫码+差异处理",
    priority: "P2",
    group: "M3 库存盘点",
    moduleCode: "M3",
    slug: "pda-m3-005",
  },
  {
    storyId: "US-M3-006",
    title: "库内移库",
    end: "pda",
    reason: "PDA 扫码移库",
    priority: "P2",
    group: "M3 库内移库",
    moduleCode: "M3",
    slug: "pda-m3-006",
  },
  {
    storyId: "US-M3-009",
    title: "库存预警",
    end: "pc",
    reason: "预警规则+告警列表",
    priority: "P2",
    group: "M3 库存预警",
    moduleCode: "M3",
    slug: "pc-m3-009",
  },
  {
    storyId: "US-M3-010",
    title: "ABC 分类管理",
    end: "pc",
    reason: "分类规则+结果展示",
    priority: "P2",
    group: "M3 ABC 分类管理",
    moduleCode: "M3",
    slug: "pc-m3-010",
  },
  {
    storyId: "US-M3-011",
    title: "库位历史追踪",
    end: "pc",
    reason: "库位时间线",
    priority: "P2",
    group: "M3 库位历史追踪",
    moduleCode: "M3",
    slug: "pc-m3-011",
  },
  {
    storyId: "US-M4-001",
    title: "出库订单管理",
    end: "pc",
    reason: "订单列表+状态筛选+详情",
    priority: "P3",
    group: "M4 出库订单管理",
    moduleCode: "M4",
    slug: "pc-m4-001",
  },
  {
    storyId: "US-M4-002",
    title: "波次规划",
    end: "pc",
    reason: "波次创建+订单分配+策略",
    priority: "P3",
    group: "M4 波次规划",
    moduleCode: "M4",
    slug: "pc-m4-002",
  },
  {
    storyId: "US-M4-003",
    title: "PDA 拣选作业",
    end: "pda",
    reason: "PDA 拣选路径+扫码确认",
    priority: "P3",
    group: "M4 PDA 拣选作业",
    moduleCode: "M4",
    slug: "pda-m4-003",
  },
  {
    storyId: "US-M4-004",
    title: "出库复核",
    end: "pda",
    reason: "PDA/PAD 扫码复核",
    priority: "P3",
    group: "M4 出库复核",
    moduleCode: "M4",
    slug: "pda-m4-004",
  },
  {
    storyId: "US-M4-004",
    title: "出库复核",
    end: "pad",
    reason: "PDA/PAD 扫码复核",
    priority: "P3",
    group: "M4 出库复核",
    moduleCode: "M4",
    slug: "pad-m4-004",
  },
  {
    storyId: "US-M4-005",
    title: "随货同行单打印",
    end: "pc",
    reason: "打印预览+GSP 格式",
    priority: "P3",
    group: "M4 随货同行单打印",
    moduleCode: "M4",
    slug: "pc-m4-005",
  },
  {
    storyId: "US-M4-005",
    title: "随货同行单打印",
    end: "pad",
    reason: "打印预览+GSP 格式",
    priority: "P3",
    group: "M4 随货同行单打印",
    moduleCode: "M4",
    slug: "pad-m4-005",
  },
  {
    storyId: "US-M4-006",
    title: "发货与交接",
    end: "pda",
    reason: "PDA 交接扫码+PC 确认",
    priority: "P3",
    group: "M4 发货与交接",
    moduleCode: "M4",
    slug: "pda-m4-006",
  },
  {
    storyId: "US-M4-006",
    title: "发货与交接",
    end: "pc",
    reason: "PDA 交接扫码+PC 确认",
    priority: "P3",
    group: "M4 发货与交接",
    moduleCode: "M4",
    slug: "pc-m4-006",
  },
  {
    storyId: "US-M4-007",
    title: "出库进度看板",
    end: "pc",
    reason: "实时进度大屏",
    priority: "P3",
    group: "M4 出库进度看板",
    moduleCode: "M4",
    slug: "pc-m4-007",
  },
  {
    storyId: "US-M4-007",
    title: "出库进度看板",
    end: "pad",
    reason: "实时进度大屏",
    priority: "P3",
    group: "M4 出库进度看板",
    moduleCode: "M4",
    slug: "pad-m4-007",
  },
  {
    storyId: "US-M4-008",
    title: "出库退货处理",
    end: "pda",
    reason: "PDA 退货验收+PC 审批",
    priority: "P3",
    group: "M4 出库退货处理",
    moduleCode: "M4",
    slug: "pda-m4-008",
  },
  {
    storyId: "US-M4-008",
    title: "出库退货处理",
    end: "pc",
    reason: "PDA 退货验收+PC 审批",
    priority: "P3",
    group: "M4 出库退货处理",
    moduleCode: "M4",
    slug: "pc-m4-008",
  },
  {
    storyId: "US-M4-010",
    title: "拣选路径策略",
    end: "pc",
    reason: "路径可视化+策略配置",
    priority: "P3",
    group: "M4 拣选路径策略",
    moduleCode: "M4",
    slug: "pc-m4-010",
  },
  {
    storyId: "US-M4-011",
    title: "合并发货与拆单",
    end: "pc",
    reason: "合并/拆单规则+预览",
    priority: "P3",
    group: "M4 合并发货与拆单",
    moduleCode: "M4",
    slug: "pc-m4-011",
  },
  {
    storyId: "US-M5-001",
    title: "冷链设备台账",
    end: "pc",
    reason: "设备列表+校准记录",
    priority: "P2",
    group: "M5 冷链设备台账",
    moduleCode: "M5",
    slug: "pc-m5-001",
  },
  {
    storyId: "US-M5-002",
    title: "温控数据接入与展示",
    end: "pc",
    reason: "温度曲线+实时监控",
    priority: "P2",
    group: "M5 温控数据接入与展示",
    moduleCode: "M5",
    slug: "pc-m5-002",
  },
  {
    storyId: "US-M5-003",
    title: "温度超标事件接入与联动",
    end: "pc",
    reason: "超标告警+批次隔离联动",
    priority: "P2",
    group: "M5 温度超标事件接入与联动",
    moduleCode: "M5",
    slug: "pc-m5-003",
  },
  {
    storyId: "US-M6-001",
    title: "GSP 法定台账自动生成",
    end: "pc",
    reason: "台账模板+生成+导出",
    priority: "P1",
    group: "M6 GSP 法定台账自动生成",
    moduleCode: "M6",
    slug: "pc-m6-001",
  },
  {
    storyId: "US-M6-002",
    title: "审计追踪查询",
    end: "pc",
    reason: "高级查询+时间线（与H2-002联动）",
    priority: "P1",
    group: "M6 审计追踪查询",
    moduleCode: "M6",
    slug: "pc-m6-002",
  },
  {
    storyId: "US-M6-003",
    title: "业务报表",
    end: "pc",
    reason: "多维报表+图表+导出",
    priority: "P1",
    group: "M6 业务报表",
    moduleCode: "M6",
    slug: "pc-m6-003",
  },
  {
    storyId: "US-M6-004",
    title: "特殊管理药品专用台账",
    end: "pc",
    reason: "麻精/放射/血液制品专用格式",
    priority: "P1",
    group: "M6 特殊管理药品专用台账",
    moduleCode: "M6",
    slug: "pc-m6-004",
  },
  {
    storyId: "US-M8-001",
    title: "自动补货算法（门店水位）",
    end: "pc",
    reason: "水位配置+补货建议预览",
    priority: "P4",
    group: "M8 自动补货算法",
    moduleCode: "M8",
    slug: "pc-m8-001",
  },
  {
    storyId: "US-M8-002",
    title: "越库作业（Cross-Docking）",
    end: "pda",
    reason: "PDA 越库扫码+PC 调度",
    priority: "P4",
    group: "M8 越库作业",
    moduleCode: "M8",
    slug: "pda-m8-002",
  },
  {
    storyId: "US-M8-002",
    title: "越库作业（Cross-Docking）",
    end: "pc",
    reason: "PDA 越库扫码+PC 调度",
    priority: "P4",
    group: "M8 越库作业",
    moduleCode: "M8",
    slug: "pc-m8-002",
  },
  {
    storyId: "US-M9-001",
    title: "计费规则配置",
    end: "pc",
    reason: "多维计费规则编辑器",
    priority: "P2",
    group: "M9 计费规则配置",
    moduleCode: "M9",
    slug: "pc-m9-001",
  },
  {
    storyId: "US-M9-003",
    title: "账单管理",
    end: "pc",
    reason: "账单列表+明细+对账+导出",
    priority: "P2",
    group: "M9 账单管理",
    moduleCode: "M9",
    slug: "pc-m9-003",
  },
  {
    storyId: "US-M10-002",
    title: "在途温控数据接入",
    end: "pc",
    reason: "在途温度曲线+地图",
    priority: "P4",
    group: "M10 在途温控数据接入",
    moduleCode: "M10",
    slug: "pc-m10-002",
  },
  {
    storyId: "US-M10-003",
    title: "容器回收追踪",
    end: "pc",
    reason: "PDA 扫码回收+PC 追踪",
    priority: "P4",
    group: "M10 容器回收追踪",
    moduleCode: "M10",
    slug: "pc-m10-003",
  },
  {
    storyId: "US-M10-003",
    title: "容器回收追踪",
    end: "pda",
    reason: "PDA 扫码回收+PC 追踪",
    priority: "P4",
    group: "M10 容器回收追踪",
    moduleCode: "M10",
    slug: "pda-m10-003",
  },
  {
    storyId: "US-M10-004",
    title: "出库订单与 TMS 协作",
    end: "pc",
    reason: "订单推送状态+调度结果",
    priority: "P4",
    group: "M10 出库订单与 TMS 协作",
    moduleCode: "M10",
    slug: "pc-m10-004",
  },
  {
    storyId: "US-TE-004",
    title: "任务优先级规则",
    end: "pc",
    reason: "优先级规则编辑器",
    priority: "P2",
    group: "TE 任务优先级规则",
    moduleCode: "TE",
    slug: "pc-te-004",
  },
  {
    storyId: "US-TE-005",
    title: "任务分配",
    end: "pc",
    reason: "分配策略+手动调整",
    priority: "P2",
    group: "TE 任务分配",
    moduleCode: "TE",
    slug: "pc-te-005",
  },
  {
    storyId: "US-TE-006",
    title: "任务释放控制",
    end: "pc",
    reason: "释放规则+队列管理",
    priority: "P2",
    group: "TE 任务释放控制",
    moduleCode: "TE",
    slug: "pc-te-006",
  },
  {
    storyId: "US-TE-007",
    title: "任务合并",
    end: "pc",
    reason: "合并规则+预览",
    priority: "P2",
    group: "TE 任务合并",
    moduleCode: "TE",
    slug: "pc-te-007",
  },
  {
    storyId: "US-TE-008",
    title: "任务执行（PDA）",
    end: "pda",
    reason: "PDA 任务列表+执行+完成",
    priority: "P2",
    group: "TE 任务执行",
    moduleCode: "TE",
    slug: "pda-te-008",
  },
  {
    storyId: "US-TE-009",
    title: "任务跟踪看板",
    end: "pc",
    reason: "实时任务大屏",
    priority: "P2",
    group: "TE 任务跟踪看板",
    moduleCode: "TE",
    slug: "pc-te-009",
  },
  {
    storyId: "US-TE-009",
    title: "任务跟踪看板",
    end: "pad",
    reason: "实时任务大屏",
    priority: "P2",
    group: "TE 任务跟踪看板",
    moduleCode: "TE",
    slug: "pad-te-009",
  },
  {
    storyId: "US-TE-010",
    title: "任务绩效统计",
    end: "pc",
    reason: "绩效报表+排名",
    priority: "P2",
    group: "TE 任务绩效统计",
    moduleCode: "TE",
    slug: "pc-te-010",
  },
  {
    storyId: "US-RP-001",
    title: "补货阈值管理",
    end: "pc",
    reason: "阈值配置+批量设置",
    priority: "P2",
    group: "RP 补货阈值管理",
    moduleCode: "RP",
    slug: "pc-rp-001",
  },
  {
    storyId: "US-RP-002",
    title: "日常补货（阈值触发）",
    end: "pda",
    reason: "PDA 补货任务执行",
    priority: "P2",
    group: "RP 日常补货",
    moduleCode: "RP",
    slug: "pda-rp-002",
  },
  {
    storyId: "US-RP-003",
    title: "波次补货（紧急触发）",
    end: "pda",
    reason: "PDA 紧急补货",
    priority: "P2",
    group: "RP 波次补货",
    moduleCode: "RP",
    slug: "pda-rp-003",
  },
  {
    storyId: "US-RP-004",
    title: "拣选补拣（兜底触发）",
    end: "pda",
    reason: "PDA 补拣",
    priority: "P2",
    group: "RP 拣选补拣",
    moduleCode: "RP",
    slug: "pda-rp-004",
  },
  {
    storyId: "US-RP-005",
    title: "补货记录与报表",
    end: "pc",
    reason: "补货记录列表+统计",
    priority: "P2",
    group: "RP 补货记录与报表",
    moduleCode: "RP",
    slug: "pc-rp-005",
  },
  {
    storyId: "US-PK-001",
    title: "包装站工位管理",
    end: "pc",
    reason: "工位配置+状态",
    priority: "P3",
    group: "PK 包装站工位管理",
    moduleCode: "PK",
    slug: "pc-pk-001",
  },
  {
    storyId: "US-PK-001",
    title: "包装站工位管理",
    end: "pad",
    reason: "工位配置+状态",
    priority: "P3",
    group: "PK 包装站工位管理",
    moduleCode: "PK",
    slug: "pad-pk-001",
  },
  {
    storyId: "US-PK-002",
    title: "装箱作业",
    end: "pad",
    reason: "PAD 装箱扫码+Put-to-Light",
    priority: "P3",
    group: "PK 装箱作业",
    moduleCode: "PK",
    slug: "pad-pk-002",
  },
  {
    storyId: "US-PK-003",
    title: "称重校验",
    end: "pad",
    reason: "电子秤对接+差异提示",
    priority: "P3",
    group: "PK 称重校验",
    moduleCode: "PK",
    slug: "pad-pk-003",
  },
  {
    storyId: "US-PK-004",
    title: "保温箱配置（冷链）",
    end: "pc",
    reason: "保温箱规格+温区匹配",
    priority: "P3",
    group: "PK 保温箱配置",
    moduleCode: "PK",
    slug: "pc-pk-004",
  },
  {
    storyId: "US-PK-005",
    title: "追溯码出库核验",
    end: "pad",
    reason: "PAD 扫码核验",
    priority: "P3",
    group: "PK 追溯码出库核验",
    moduleCode: "PK",
    slug: "pad-pk-005",
  },
  {
    storyId: "US-PK-006",
    title: "快递面单打印",
    end: "pad",
    reason: "面单预览+打印",
    priority: "P3",
    group: "PK 快递面单打印",
    moduleCode: "PK",
    slug: "pad-pk-006",
  },
  {
    storyId: "US-VR-001",
    title: "校验规则配置",
    end: "pc",
    reason: "规则编辑器+条件组合",
    priority: "P2",
    group: "VR 校验规则配置",
    moduleCode: "VR",
    slug: "pc-vr-001",
  },
  {
    storyId: "US-VR-003",
    title: "校验异常人工处理",
    end: "pc",
    reason: "异常队列+处理表单",
    priority: "P2",
    group: "VR 校验异常人工处理",
    moduleCode: "VR",
    slug: "pc-vr-003",
  },
  {
    storyId: "US-VR-005",
    title: "校验规则测试",
    end: "pc",
    reason: "规则沙箱测试+结果",
    priority: "P2",
    group: "VR 校验规则测试",
    moduleCode: "VR",
    slug: "pc-vr-005",
  },
  {
    storyId: "US-VR-006",
    title: "双人策略矩阵规则",
    end: "pc",
    reason: "矩阵配置+策略预览",
    priority: "P2",
    group: "VR 双人策略矩阵规则",
    moduleCode: "VR",
    slug: "pc-vr-006",
  },
  {
    storyId: "US-QL-001",
    title: "质量联系单类型与审批模板配置",
    end: "pc",
    reason: "模板配置+审批流设计",
    priority: "P3",
    group: "QL 质量联系单类型与审批模板配置",
    moduleCode: "QL",
    slug: "pc-ql-001",
  },
  {
    storyId: "US-QL-002",
    title: "创建质量联系单",
    end: "pda",
    reason: "PDA 触发+PC 补充",
    priority: "P3",
    group: "QL 创建质量联系单",
    moduleCode: "QL",
    slug: "pda-ql-002",
  },
  {
    storyId: "US-QL-002",
    title: "创建质量联系单",
    end: "pc",
    reason: "PDA 触发+PC 补充",
    priority: "P3",
    group: "QL 创建质量联系单",
    moduleCode: "QL",
    slug: "pc-ql-002",
  },
  {
    storyId: "US-QL-003",
    title: "质量联系单审批",
    end: "pc",
    reason: "审批流程+意见+驳回",
    priority: "P3",
    group: "QL 质量联系单审批",
    moduleCode: "QL",
    slug: "pc-ql-003",
  },
  {
    storyId: "US-QL-005",
    title: "质量联系单查询与统计",
    end: "pc",
    reason: "列表+统计+导出",
    priority: "P3",
    group: "QL 质量联系单查询与统计",
    moduleCode: "QL",
    slug: "pc-ql-005",
  },
  {
    storyId: "US-SA-001",
    title: "报损单管理",
    end: "pda",
    reason: "PDA 发起+PC 审批",
    priority: "P3",
    group: "SA 报损单管理",
    moduleCode: "SA",
    slug: "pda-sa-001",
  },
  {
    storyId: "US-SA-001",
    title: "报损单管理",
    end: "pc",
    reason: "PDA 发起+PC 审批",
    priority: "P3",
    group: "SA 报损单管理",
    moduleCode: "SA",
    slug: "pc-sa-001",
  },
  {
    storyId: "US-SA-002",
    title: "报溢单管理",
    end: "pda",
    reason: "PDA 发起+PC 审批",
    priority: "P3",
    group: "SA 报溢单管理",
    moduleCode: "SA",
    slug: "pda-sa-002",
  },
  {
    storyId: "US-SA-002",
    title: "报溢单管理",
    end: "pc",
    reason: "PDA 发起+PC 审批",
    priority: "P3",
    group: "SA 报溢单管理",
    moduleCode: "SA",
    slug: "pc-sa-002",
  },
  {
    storyId: "US-SA-003",
    title: "报损报溢查询与统计",
    end: "pc",
    reason: "列表+统计+导出",
    priority: "P3",
    group: "SA 报损报溢查询与统计",
    moduleCode: "SA",
    slug: "pc-sa-003",
  },
  {
    storyId: "US-RC-002",
    title: "差异处理",
    end: "pc",
    reason: "差异列表+处理流程",
    priority: "P3",
    group: "RC 差异处理",
    moduleCode: "RC",
    slug: "pc-rc-002",
  },
  {
    storyId: "US-RC-003",
    title: "手动触发对账",
    end: "pc",
    reason: "触发按钮+进度",
    priority: "P3",
    group: "RC 手动触发对账",
    moduleCode: "RC",
    slug: "pc-rc-003",
  },
  {
    storyId: "US-RC-004",
    title: "对账报表",
    end: "pc",
    reason: "对账结果+历史",
    priority: "P3",
    group: "RC 对账报表",
    moduleCode: "RC",
    slug: "pc-rc-004",
  },
  {
    storyId: "US-DI-001",
    title: "药检单平台对接配置",
    end: "pc",
    reason: "对接配置+测试连接",
    priority: "P3",
    group: "DI 药检单平台对接配置",
    moduleCode: "DI",
    slug: "pc-di-001",
  },
  {
    storyId: "US-DI-002",
    title: "扫码批量查询药检单",
    end: "pda",
    reason: "PDA 扫码查询",
    priority: "P3",
    group: "DI 扫码批量查询药检单",
    moduleCode: "DI",
    slug: "pda-di-002",
  },
  {
    storyId: "US-DI-003",
    title: "药检单存储与查看",
    end: "pc",
    reason: "药检单详情+PDF 预览",
    priority: "P3",
    group: "DI 药检单存储与查看",
    moduleCode: "DI",
    slug: "pc-di-003",
  },
  {
    storyId: "US-BA-001",
    title: "创建批号调整单",
    end: "pc",
    reason: "调整单表单+原因选择",
    priority: "P3",
    group: "BA 创建批号调整单",
    moduleCode: "BA",
    slug: "pc-ba-001",
  },
  {
    storyId: "US-BA-002",
    title: "批号调整双人审批",
    end: "pc",
    reason: "审批流程",
    priority: "P3",
    group: "BA 批号调整双人审批",
    moduleCode: "BA",
    slug: "pc-ba-002",
  },
  {
    storyId: "US-BA-003",
    title: "PDA 执行批号调整",
    end: "pda",
    reason: "PDA 实物核对+扫码",
    priority: "P3",
    group: "BA PDA 执行批号调整",
    moduleCode: "BA",
    slug: "pda-ba-003",
  },
  {
    storyId: "US-TC-001",
    title: "追溯码分类管理",
    end: "pc",
    reason: "分类配置+码规则",
    priority: "P1",
    group: "TC 追溯码分类管理",
    moduleCode: "TC",
    slug: "pc-tc-001",
  },
  {
    storyId: "US-TC-002",
    title: "码库管理（大中小码）",
    end: "pc",
    reason: "码库列表+层级关系",
    priority: "P1",
    group: "TC 码库管理",
    moduleCode: "TC",
    slug: "pc-tc-002",
  },
  {
    storyId: "US-TC-003",
    title: "追溯码与商品绑定",
    end: "pc",
    reason: "绑定关系管理",
    priority: "P1",
    group: "TC 追溯码与商品绑定",
    moduleCode: "TC",
    slug: "pc-tc-003",
  },
  {
    storyId: "US-TC-004",
    title: "PDA 追溯码对应关系维护",
    end: "pda",
    reason: "PDA 扫码建立关系",
    priority: "P1",
    group: "TC PDA 追溯码对应关系维护",
    moduleCode: "TC",
    slug: "pda-tc-004",
  },
  {
    storyId: "US-TC-006",
    title: "出库追溯码核验",
    end: "pda",
    reason: "扫码核验+差异提示",
    priority: "P1",
    group: "TC 出库追溯码核验",
    moduleCode: "TC",
    slug: "pda-tc-006",
  },
  {
    storyId: "US-TC-006",
    title: "出库追溯码核验",
    end: "pad",
    reason: "扫码核验+差异提示",
    priority: "P1",
    group: "TC 出库追溯码核验",
    moduleCode: "TC",
    slug: "pad-tc-006",
  },
  {
    storyId: "US-TC-007",
    title: "\"码上放心\"平台上报",
    end: "pc",
    reason: "上报状态+重试+日志",
    priority: "P1",
    group: "TC \"码上放心\"平台上报",
    moduleCode: "TC",
    slug: "pc-tc-007",
  },
  {
    storyId: "US-MPM-002",
    title: "映射规则配置",
    end: "pc",
    reason: "规则编辑器+条件",
    priority: "P1",
    group: "MPM 映射规则配置",
    moduleCode: "MPM",
    slug: "pc-mpm-002",
  },
  {
    storyId: "US-MPM-003",
    title: "待映射队列与质量联系单触发",
    end: "pc",
    reason: "队列列表+处理",
    priority: "P1",
    group: "MPM 待映射队列与质量联系单触发",
    moduleCode: "MPM",
    slug: "pc-mpm-003",
  },
  {
    storyId: "US-MPM-005",
    title: "反向追溯与映射溯源",
    end: "pc",
    reason: "追溯链路可视化",
    priority: "P1",
    group: "MPM 反向追溯与映射溯源",
    moduleCode: "MPM",
    slug: "pc-mpm-005",
  },
  {
    storyId: "US-MPM-006",
    title: "交易类型字典管理（PIX 三码）",
    end: "pc",
    reason: "字典+映射关系",
    priority: "P1",
    group: "MPM 交易类型字典管理",
    moduleCode: "MPM",
    slug: "pc-mpm-006",
  },
];
