/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/audit/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_audit_events"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["healthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description 审计事件操作者摘要。 */
        AuditActor: {
            /**
             * Format: uuid
             * @description 操作者 ID。
             */
            actor_id: string;
            /** @description 操作者名称。 */
            actor_name: string;
            /** @description JWT jti，用于追溯登录态。 */
            jti: string;
            /**
             * Format: uuid
             * @description 操作者所属货主 ID。
             */
            owner_id: string;
        };
        /** @description 审计事件。 */
        AuditEvent: {
            /** @description 事件动作。 */
            action: string;
            actor: components["schemas"]["AuditActor"];
            /** @description 变更详情。 */
            diff: {
                [key: string]: unknown;
            };
            /**
             * Format: int64
             * @description 审计事件 ID。
             */
            id: number;
            /**
             * Format: date-time
             * @description 发生时间。
             */
            occurred_at: string;
            /**
             * Format: uuid
             * @description 被审计记录所属货主 ID。
             */
            owner_id: string;
            /** @description 资源实例 ID。 */
            resource_id: string;
            /** @description 资源类型。 */
            resource_type: string;
            /** @description 审计 trace ID。 */
            trace_id: string;
        };
        /** @description 审计事件分页响应。 */
        AuditEventListResponse: {
            /** @description 事件列表。 */
            data: components["schemas"]["AuditEvent"][];
            /** @description 下一页游标；为空表示无更多数据。 */
            next_cursor?: string | null;
        };
        /** @description 当前登录用户摘要。 */
        CurrentUser: {
            /** @description 展示名。 */
            display_name: string;
            /** @description 货主编码。 */
            owner_code: string;
            /**
             * Format: uuid
             * @description 货主 ID。
             */
            owner_id: string;
            /** @description 当前权限码列表。 */
            permissions: string[];
            /** @description 当前角色列表。 */
            roles: string[];
            /**
             * Format: uuid
             * @description 用户 ID。
             */
            user_id: string;
            /** @description 用户名。 */
            username: string;
        };
        /** @description 统一错误响应。 */
        ErrorResponse: {
            /** @description 业务错误码。 */
            code: string;
            /** @description 关联详情。 */
            details: {
                [key: string]: unknown;
            };
            /** @description 中文错误消息。 */
            message: string;
            /** @description 重试提示。 */
            retry_hint?: string | null;
            /** @description 严重度。 */
            severity: string;
            /** @description 链路追踪 ID。 */
            trace_id: string;
        };
        /** @description 健康检查响应。 */
        HealthzResponse: {
            /**
             * Format: date-time
             * @description 文档生成时间。
             */
            generated_at: string;
            /** @description 服务状态。 */
            status: string;
            /** @description 契约版本。 */
            version: string;
        };
        /** @description 登录请求。 */
        LoginRequest: {
            /** @description 货主编码。 */
            owner_code: string;
            /** @description 登录密码。 */
            password: string;
            /** @description 登录账号。 */
            username: string;
        };
        /** @description 登录成功响应。 */
        LoginResponse: {
            /** @description Bearer token。 */
            access_token: string;
            /**
             * Format: date-time
             * @description 过期时间。
             */
            expires_at: string;
            /** @description token 类型。 */
            token_type: string;
            user: components["schemas"]["CurrentUser"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_audit_events: {
        parameters: {
            query?: {
                /** @description 按资源类型过滤 */
                resource_type?: string | null;
                /** @description 按操作者过滤 */
                actor_id?: string | null;
                /** @description 开始时间（RFC3339） */
                from?: string | null;
                /** @description 结束时间（RFC3339） */
                to?: string | null;
                /** @description 每页条数 */
                limit?: number | null;
                /** @description 分页游标 */
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 审计事件列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditEventListResponse"];
                };
            };
            /** @description 未登录 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description 登录成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description 认证失败 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 当前登录用户 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentUser"];
                };
            };
            /** @description 未登录 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    healthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 服务健康 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthzResponse"];
                };
            };
        };
    };
}
