//! 主仓 OpenAPI 契约。

pub mod admin_menu;
pub mod admin_menu_handlers;
mod admin_menu_idempotency;
mod admin_menu_model;
mod admin_menu_repository;
pub mod alert_dashboard;
pub mod alert_dashboard_handlers;
pub mod alert_definition_handlers;
pub mod alert_definition_repository;
pub mod alert_definition_service;
pub mod alert_engine_job;
pub mod alert_escalation;
pub mod alert_escalation_handlers;
pub mod alert_instance_handlers;
pub mod alert_instance_repository;
pub mod alert_lifecycle_service;
pub mod api_key_auth;
pub mod api_key_expiry;
pub mod api_key_handlers;
pub mod api_key_repository;
pub mod api_key_service;
pub mod audit;
pub mod auth;
pub mod auth_handlers;
pub mod auth_repository;
pub mod auth_service;
pub mod billing;
pub mod cold_chain;
pub mod config_center;
pub mod deploy_audit;
pub mod dock_appointment_handlers;
pub mod dock_appointment_repository;
pub mod dock_handlers;
pub mod dock_repository;
pub mod document_numbering;
pub mod document_numbering_handlers;
mod document_numbering_repository;
pub mod drug_inspection_copy_processor;
mod drug_inspection_copy_projection;
pub mod drug_inspection_copy_service;
pub mod drug_inspection_document_handlers;
pub mod drug_inspection_document_repository;
pub mod drug_inspection_handlers;
pub mod drug_inspection_portal_bridge;
pub mod drug_inspection_repository;
pub mod drug_inspection_stamp_handlers;
pub mod dual_person_policy;
pub mod dual_person_policy_handlers;
pub mod express;
pub mod feature_flags;
pub mod file_attachment;
pub mod file_attachment_handlers;
pub mod file_attachment_repository;
pub mod h2_lifecycle;
pub mod h2_lifecycle_handlers;
pub mod h8_erp_connectors;
pub mod h8_erp_interface_tables;
pub mod h8_erp_messages;
pub mod h8_inbound;
pub mod inbound;
pub mod inventory;
pub mod inventory_expiry_job;
pub mod inventory_status_config;
pub mod inventory_status_config_handlers;
pub mod master_data;
pub mod master_data_handlers;
pub mod master_data_postgres;
mod openapi_contract;
pub mod operation_context;
pub mod outbound;
pub mod packing_station;
pub mod parameter_mapping;
pub mod pdf_document;
pub mod print_device;
pub mod print_device_handlers;
pub mod print_orchestration;
pub mod print_orchestration_handlers;
pub mod print_orchestration_job;
pub mod print_template;
pub mod print_template_handlers;
pub mod quality_liaison;
pub mod quality_liaison_handlers;
pub mod reconciliation;
mod reconciliation_claims;
pub mod reconciliation_handlers;
pub mod reconciliation_query;
pub mod reports;
pub mod reports_handlers;
pub mod resilience;
pub mod retail_chain;
pub mod role_management;
mod role_management_models;
pub mod secrets;
pub mod state_machine;
pub mod stock_adjustment;
pub mod stock_adjustment_handlers;
mod sync;
pub mod system_dictionary;
pub mod system_dictionary_handlers;
pub mod task_engine;
pub mod task_engine_handlers;
pub mod task_release_job;
pub mod task_type;
pub mod task_type_handlers;
pub mod tms_plus;
pub mod traceability_code;
pub(crate) mod warehouse_scope;
pub mod wave3_handlers;
pub mod wave3_repository;
pub mod wave4_handlers;
pub mod wave4_repository;
pub mod wave4_service;
pub mod wave5_handlers;
pub mod wave5_repository;
pub mod wechat_notify;
mod wechat_notify_idempotency;
pub mod wechat_notify_service;

mod openapi_doc;
mod openapi_paths;

#[cfg(test)]
mod openapi_tests;

pub use openapi_doc::ApiDoc;
