pub use crate::document_numbering::{
    DocumentNumberRule, DocumentNumberRuleListResponse, SetDocumentNumberRuleEnabledRequest,
    UpsertDocumentNumberRuleRequest,
};
pub use crate::print_template::{
    PrintFieldDefinition, PrintFieldDefinitionListResponse, PrintFieldLibraryListResponse,
    PrintFieldLibrarySummary, PrintRecord, PrintTemplateBinding, PrintTemplateListResponse,
    PrintTemplatePreviewRequest, PrintTemplatePreviewResponse, PrintTemplatePrintRequest,
    PrintTemplateScope, PrintTemplateSummary, PrintTemplateVersion,
    PrintTemplateVersionListResponse, ResolvePrintTemplateRequest, ResolvePrintTemplateResponse,
    SavePrintTemplateRequest,
};
pub use wms_domain::{
    AdminMenuButtonPermission, AdminMenuNode, AdminMenuTreeResponse, AdminMenuVersion, AuditActor,
    AuditArchivePartitionState, AuditArchivePartitionStateListResponse, AuditArchiveRunRequest,
    AuditArchiveRunResponse, AuditEvent, AuditEventListResponse, BatchCreateLocationsRequest,
    BatchEnableAdminMenuRequest, BillingAccount, BillingChargeCalculation, BillingContract,
    BillingRule, BillingStatement, BusinessArchiveJob, BusinessRetentionPolicy,
    BusinessRetentionPolicyListResponse, CalculateBillingChargesRequest,
    CancelExpressWaybillRequest, ChangeInventoryStatusRequest, ColdChainDevice,
    CompletePickTaskRequest, ConfigEntry, ConfirmBillingStatementRequest,
    ConfirmContainerRecoveryRequest, ContainerRecovery, CreateAdminMenuNodeRequest,
    CreateBillingAccountRequest, CreateBillingContractRequest, CreateBillingRuleRequest,
    CreateColdChainDeviceRequest, CreateCrossdockPlanRequest, CreateCustomerRequest,
    CreateExpressWaybillRequest, CreateH4ApprovalRequest, CreateLocationRequest,
    CreateOutboundOrderLineRequest, CreateOutboundOrderRequest, CreateOutboundWaveRequest,
    CreatePackJobRequest, CreatePackingStationRequest, CreateProductRequest,
    CreateReceivingOrderRequest, CreateRetailReplenishmentSuggestionRequest,
    CreateSpecialDrugCategoryRequest, CreateSupplierRequest, CreateWarehouseRequest,
    CreateWarehouseZoneRequest, CrossdockPlan, CurrentUser, Customer, CustomerListResponse,
    DisableSystemDictionaryItemRequest, DisposeTemperatureExcursionRequest,
    DocumentNumberAllocation, DocumentNumberAllocationListResponse, DriverTask,
    DriverTaskListResponse, ErrorResponse, EventDelivery, EventDeliveryListResponse,
    EventDeliveryNackRequest, ExecuteMappingRequest, ExecuteMappingResponse, ExpressCarrier,
    ExpressCarrierListResponse, ExpressRoutingRule, ExpressRoutingRuleListResponse,
    ExpressTrackingEvent, ExpressTrackingResponse, ExpressWaybill, FeatureFlagArchiveRequest,
    FeatureFlagArchiveResult, FeatureFlagBatchImportRequest, FeatureFlagBatchImportResult,
    FeatureFlagConfig, FeatureFlagExportResponse, FeatureFlagMigrationResult,
    FeatureFlagReconcileReport, FeatureFlagSourceSwitchRequest, FeatureFlagSourceSwitchResponse,
    GenerateBillingStatementRequest, GspLedgerReport, GspLedgerRow, H4ApprovalCallbackRequest,
    H4ApprovalRecord, H4NotificationConfig, H4NotificationConfigListResponse, H4NotificationRecord,
    H4NotificationRecordListResponse, H4WechatSettings, H4WechatSettingsResponse,
    H4WechatSettingsTestResponse, HealthzResponse, IngestTemperatureExcursionRequest,
    IngestTemperatureReadingRequest, IngestTransitTemperatureRequest, InspectReceivingOrderRequest,
    InspectionSignatureRecord, InventoryBatch, InventoryBatchListResponse, InventoryMovement,
    Location, LocationListResponse, LoginRequest, LoginResponse, MappingDictionary,
    MappingQueueItem, MappingRule, MappingTraceResponse, OutboundOrder, OutboundOrderLine,
    OutboundOrderListResponse, OutboundWave, PackJob, PackingStation, PageMeta,
    PlanBusinessArchiveJobRequest, PrintWaybillRequest, Product, ProductListResponse,
    PublishAdminMenuRequest, PutawayInventoryRequest, PutawayRecord, PutawayRequest,
    ReceiveReceivingOrderRequest, ReceiveTmsDispatchRequest, ReceivingInspectionRecord,
    ReceivingOrder, ReceivingOrderLine, ReceivingOrderListResponse, ReceivingOrderReceipt,
    RejectReceivingOrderRequest, ReportQueryRequest, ReportQueryResponse, ReportRow,
    ResilienceStatus, RetailReplenishmentSuggestion, ReviewOutboundOrderRequest,
    RollbackAdminMenuRequest, SendH4NotificationRequest, ShipOutboundOrderRequest,
    SignInspectionRequest, SpecialDrugCategory, SpecialDrugCategoryListResponse,
    StateMachineDefinition, StateMachineDefinitionListResponse, StateMachineState,
    StateMachineTransition, StateTransitionValidationResponse, StoreDashboardResponse, Supplier,
    SupplierListResponse, SystemDictionaryCategory, SystemDictionaryImpactPreview,
    SystemDictionaryImpactReference, SystemDictionaryItem, SystemDictionaryItemListResponse,
    TemperatureExcursionDispositionResponse, TemperatureExcursionEvent,
    TemperatureExcursionEventListResponse, TemperatureReading, TmsDispatch,
    TraceabilityOutboundReport, TraceabilityOutboundReportRequest, TraceabilityStatusChangeEvent,
    TransitTemperatureReading, UpdateAdminMenuNodeRequest, UpdateCustomerRequest,
    UpdateLocationRequest, UpdateProductRequest, UpdateReceivingOrderRequest,
    UpdateSpecialDrugCategoryRequest, UpdateSupplierRequest, UpdateWarehouseRequest,
    UpdateWarehouseZoneRequest, UpsertAdminMenuButtonPermissionRequest,
    UpsertExpressCarrierRequest, UpsertExpressRoutingRuleRequest,
    UpsertH4NotificationConfigRequest, UpsertH4WechatSettingsRequest,
    UpsertSystemDictionaryItemRequest, Warehouse, WarehouseListResponse, WarehouseZone,
    WarehouseZoneListResponse, WeighPackJobRequest,
};

#[allow(dead_code)]
fn _h4_openapi_type_use(
    _create_approval: Option<CreateH4ApprovalRequest>,
    _approval_callback: Option<H4ApprovalCallbackRequest>,
    _approval: Option<H4ApprovalRecord>,
    _config: Option<H4NotificationConfig>,
    _config_list: Option<H4NotificationConfigListResponse>,
    _wechat_settings: Option<H4WechatSettings>,
    _wechat_settings_response: Option<H4WechatSettingsResponse>,
    _wechat_settings_test_response: Option<H4WechatSettingsTestResponse>,
    _record: Option<H4NotificationRecord>,
    _record_list: Option<H4NotificationRecordListResponse>,
    _send: Option<SendH4NotificationRequest>,
    _upsert_config: Option<UpsertH4NotificationConfigRequest>,
    _upsert_wechat_settings: Option<UpsertH4WechatSettingsRequest>,
) {
}

mod core;
mod extensions;

pub(crate) use core::*;
pub(crate) use extensions::*;
